### ISSUE TITLE
NumWorks workshop crashes Omega

### ISSUE THREAD

**Issue by MixedMatched** [Omega-Numworks/Omega#10]
#### Describe the bug
Whenever I open the NumWorks python page, the calculator crashes and must be reflashed to boot again.

#### Environment
 - Omega Version: 1.7

**Comment by quentinguidee** [comment]
Oh damn, I just checked it makes me the same ... Do you think it's a bug to report to Numworks or it only happens with our modified version?

**Comment by quentinguidee** [comment]
![Annotation 2019-08-24 142725](https://user-images.githubusercontent.com/12123721/63637301-6fc57780-c67b-11e9-92ef-a6359e0ea2ca.png)

Oh and I just saw this: the version of LavaOS is written right next to the version of Epsilon in "my devices". Don't know why but it's cool ahah!

**Comment by MixedMatched** [comment]
I think it happens because of the custom version number.

**Comment by M4xi1m3** [comment]
I got some other weird issue with the workshop : with omega installed it says the internal memory of the numworks is corrupted and asks me to install the latest update

**Comment by reini1305** [comment]
> I got some other weird issue with the workshop : with omega installed it says the internal memory of the numworks is corrupted and asks me to install the latest update
I've seen the same issue with my N0100. I had to go back to epsilon since I need my python scripts :)

**Comment by quentinguidee** [comment]
@reini1305 Thanks for the feedback & thank you for taking the time to try Omega! I think we'll release an equivalent to the workshop (if there's no way to solve this issue).

**Comment by quentinguidee** [comment]
### Similar issue (#55)

From @AlexPMLikesNumWorks
> **Describe the bug**
> 
> With this version, I cannot connect the calculator to NumWorks' Workshop for Python scripts. All connection attempts end up in having the web page stating that the calculator is not connected.
> 
> When I try to force-download Python scripts, web page says that the calculator's memory is corrupted and that I have to update to the latest version.
> 
> Is upload/download of Python scripts supported in Omega 1.10.1-0?
> 
> **Environment**
> 
> - Omega version : 1.10.1-0
> - Model : _unknown_

**Comment by M4xi1m3** [comment]
It was the custom version + username thing. Moving them in memory to have epsilon's version and patch number where the workshop expects them to be made it work again : #59.

**Comment by quentinguidee** [comment]
@reini1305 Hi! Thanks to @M4xi1m3, you can now use the Workshop with Omega and transfer your scripts :smile:

**Comment by reini1305** [comment]
> @reini1305 Hi! Thanks to @M4xi1m3, you can now use the Workshop with Omega and transfer your scripts smile
Just tried it out, works perfectly. Thanks!

**Comment by quentinguidee** [comment]
Thank you for the feedback! 👌
