### ISSUE TITLE
Shift+1 and % are buggy

### ISSUE THREAD

**Issue by RedGl0w** [Omega-Numworks/Omega#102]
#### Describe the bug
When you try to add % from the keyboard, it doesn't

This comes from : https://github.com/Omega-Numworks/Omega/commit/9e6029e52f5b15d35d608aacb55a497a8caa0467

I'm trying to find the issue and patch it (because without, I can't do https://github.com/Omega-Numworks/Omega/pull/101)

**Comment by RedGl0w** [comment]
Ok,
I've understood why the keyboardevents have been changed.
This PR can be closed now (https://github.com/Omega-Numworks/Omega/pull/101), because now, when you shift+alpha+percent, it adds a percent, but when it's not in shift, it removes the last character.
For the shift+1, on the slack, we think it must be for KhiCas apps, but I think we should find a better solution.

**Comment by RedGl0w** [comment]
But the PR didn't explained that ( @zardam please think about it next time (and don't mind my message on Ti-Planet))

**Comment by zardam** [comment]
These changes are not from me, sorry. They were intended for KhiCAS. I think there was a thead on TI-Planet about the "backspace" behavior when in alphalock (and the need to quit alpha lock to remove a character).

**Comment by RedGl0w** [comment]
Don't worry
And we found a solution that we found better (cf. My PR)
