### ISSUE TITLE
Exam mode on n0100

### ISSUE THREAD

**Issue by RedGl0w** [Omega-Numworks/Omega#106]
#### Describe the bug

When I try to go to the exam mode settings on the n0100, I got this : 
![IMG_20191226_122716](https://user-images.githubusercontent.com/43498612/71474381-65f38280-27db-11ea-8920-013bb7c2dada.jpg)
And when I poweroff and power on, I got this :
![IMG_20191226_122720](https://user-images.githubusercontent.com/43498612/71474391-73107180-27db-11ea-8df9-bb294ef73b0b.jpg)

<hr>

When I find the button to enter in exam mode, I'm asked if I want to exit exam mode
But I'm not in exam mode (and when you click on one of the button, it goes to the root of the settings app).

#### Environment
 - Omega Version: omega-dev latest (https://github.com/Omega-Numworks/Omega/tree/b7fe5b51c8dd2b5edd11252611c3af061755a7d3)

**Comment by quentinguidee** [comment]
Fixed by #107
