### ISSUE TITLE
I18n size issues

### ISSUE THREAD

**Issue by RedGl0w** [Omega-Numworks/Omega#109]
### multiplication symbol :

- French : ![image](https://user-images.githubusercontent.com/43498612/71529088-4051a080-28e3-11ea-9330-e3b864b8d35d.png)
- Spanish : ![image](https://user-images.githubusercontent.com/43498612/71529117-66774080-28e3-11ea-9c28-191bf08533fd.png)
- German :  ![image](https://user-images.githubusercontent.com/43498612/71529215-f61cef00-28e3-11ea-8752-21819a4f97e4.png)
- Portugues : ![image](https://user-images.githubusercontent.com/43498612/71529288-6166c100-28e4-11ea-8c2f-7b2871193197.png)

### Micropy version :

- French : https://github.com/orgs/Omega-Numworks/projects/5#card-30219745
- Spanish : ![image](https://user-images.githubusercontent.com/43498612/71529187-bf46d900-28e3-11ea-9f65-ceb542f3cafe.png)

**Comment by M4xi1m3** [comment]
Micro python version in French fixed with #111

**Comment by quentinguidee** [comment]
#111 & #112 are merged
