### ISSUE TITLE
Update Omega to the latest Epsilon Beta (12.0.0)

### ISSUE THREAD

**Issue by quentinguidee** [Omega-Numworks/Omega#12]
Update Omega to the latest Epsilon Beta (12.0.0)

**Comment by MixedMatched** [comment]
I think the main issues we'll have with the merge are the refactoring of calculation and the main_controller. Because symbolic calculation was removed, they removed since of the parse calls, but now that the methods of calculation are different, I'm not sure where they should go.

**Comment by quentinguidee** [comment]
Ah... I did not know they were modifying that.. we will avoid the betas for the moment then, and we will update when the 12.0 will be officially released. Thanks for pointing out this problem!

**Comment by quentinguidee** [comment]
## Checklist (O1.9-E12.0.0)

### Home

* [x] At the top of the screen should be written "OMEGA"

### Calculation

* [x] (x+2)² should return x²+4.x+4 (and undef)
* [x] Toolbox > Chemistry > Molar masses (1,2...) and (A,B...) > 120 molar masses by list (all sorted)

### Settings

* [x] Brightness > It should be 16 steps instead of 5
* [x] LED Color > 4 different colors
* [x] Exam mode > The LED shouldn't be red
* [x] About > You should see "Epsilon version" and "Omega version"
* [x] About > EXE on "Epsilon version" should display "public" or "dev"
* [x] Contributors > A list of all Omega contributors

**Comment by quentinguidee** [comment]
Hello!

I updated Omega with Epsilon 12 (master). I checked every feature, and normally everything added to Omega works again, but I'll post on Github some issues I found.

* If you want to get Omega =1.8.2 (Epsilon 11.2.0), switch to the tag "O1.8.2-E11.2".
* If you want to get Omega >1.9.0 (Epsilon 12.X.0), stay on lavaos branch.
