### ISSUE TITLE
e^(i*PI) doesn't working

### ISSUE THREAD

**Issue by NodeNXT** [Omega-Numworks/Omega#122]
#### Describe the bug
When I write "e^(i*PI)" IN "Calculation" the calculator bug. She turns off and asks me to choose my language. (The calculator is reset)

#### Environment
 - Omega Version: 1.18.2-0
 - Epsilon Version: 12.0.0
 - μPython Version: 1.11.0

**Comment by RedGl0w** [comment]
This issue should be also openned on epsilon

**Comment by NodeNXT** [comment]
No, on epsilon 12.4.0 it's working

**Comment by M4xi1m3** [comment]
Confirmed to crash n0100 and n0110. Doesn't crash simulator (linux).

**Comment by MixedMatched** [comment]
Probably a memory error then?

**Comment by M4xi1m3** [comment]
Found the issue, caused by changes in [f763563](https://github.com/Omega-Numworks/Omega/commit/f763563834be83ffae397e047191a86fc59703b3] in  poincare/src/trigonometry_cheat_table.cpp:85

**Comment by quentinguidee** [comment]
@NodeNXT This bug is now fixed in Omega 1.18.4 on the master branch! Thank you for reporting this issue 😉
