### ISSUE TITLE
Precompiled versions

### ISSUE THREAD

**Issue by quentinguidee** [Omega-Numworks/Omega#13]
#### What I want to see in the next version of Omega
Someone [here](https://www.reddit.com/r/numworks/comments/c5tbol/r%C3%A9activer_calcul_litt%C3%A9ral_dans_la_version_1120/f2l5mga/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) suggests to release precompiled versions of Omega, because it’s hard to compile on Windows

+ he suggest to make an auto install with chrome, but I don’t know if it is possible easily

**Comment by RedGl0w** [comment]
I think I gonna try to do this on my future github page. It looks simple...

**Comment by RedGl0w** [comment]
With webdfu it is simple, i think :
https://github.com/devanlai/webdfu/tree/gh-pages/dfu-util
https://devanlai.github.io/webdfu/dfu-util/
I will try to do this in my future github page. If i manage to finish it, you could integrate it if you want !

**Comment by quentinguidee** [comment]
Ooh thank you for your help!!

**Comment by RedGl0w** [comment]
Ok, I've praticaly finished for the n0100
I will add a warning for the n0110.
The url : https://redgl0w.github.io/omega/n0100/index.html

**Comment by MixedMatched** [comment]
@RedGl0w That's really cool! We could probably set up a GitHub app to automatically compile Omega and copy the binaries to your repository. That way, the binaries don't need to be manually compiled every time Omega is updated. 

Also, if we were somehow able to compile in the website, instead of manually or with an external app, system options, like uploadable apps, removing system apps, or easily inputed themes, could be added.

**Comment by quentinguidee** [comment]
When you've finished this, can you publish it in the GitHub organization (Omega-Numworks) I just created? In this way, we centralize everything here!
Otherwise, I just tested it, and despite some problems I managed to install it easily, so thank you very much!

**Comment by quentinguidee** [comment]
Thank you very much for this 💯 ! I close this issue. If you want to update this side project, please post issues here : [https://github.com/Omega-Numworks/installer](https://github.com/Omega-Numworks/installer)
