### ISSUE TITLE
Quick URL to install Omega

### ISSUE THREAD

**Issue by cent20net** [Omega-Numworks/Omega#134]
~~Hier j'ai du donner l'adresse à un élève pour installer Omega ... La trouver a été difficile.
Il n'y a rien sur la page https://github.com/Omega-Numworks/Omega ou alors j'ai pas vu.~~

~~Ne serait-il pas possible que dans le à propos, en cliquant sur Omega, un pop up s'ouvre et indique une URL courte ou trouver la page d'installation de Omega ?~~

~~Bon il n'y a aucun nom de domaine avec Omega disponible ou des trucs des exotiques.
Si vous voulez une redirection rapide et courte, je peux affecter un sous domaine genre omega.undomainequejepossede.tld et faire pointer cette URL vers la page de votre choix, mais une URL courte est vraiment une bonne idée.~~

---

Yesterday I had to give the address to a student to install Omega ... Finding it was difficult.
There is nothing on the page https://github.com/Omega-Numworks/Omega or so I have not seen.

Wouldn't it be possible that in the about, by clicking on Omega, a pop up opens and indicates a short URL or find the Omega installation page?

Okay there is no domain name with Omega available or exotic stuff.
If you want a quick and short redirect, I can assign a subdomain like omega.undomainequejepossede.tld and point this URL to the page of your choice, but a short URL is really a good idea.

**Comment by M4xi1m3** [comment]
Maybe we could add a QR code in the about submenu? (like Settings > About > Website and then you get the qr-code)

**Comment by RedGl0w** [comment]
Done with omega app

**Comment by quentinguidee** [comment]
Thank you for the issue! This should be released with Omega 1.20 ;)
