### ISSUE TITLE
Omega in Italy

### ISSUE THREAD

**Issue by quentinguidee** [Omega-Numworks/Omega#138]
#### What I want to see in the next version of Omega
In Italy, the symbolic calculation must be disable, even if the calculator is not in exam mode.

So, I was thinking of a screen that appears just after the choice of language, which offers to choose your country (or group of countries), and which changes parameters definitively according to this choice.

**Comment by RedGl0w** [comment]
The led should be specific to a specific exam mode

**Comment by quentinguidee** [comment]
Yes but in Italy it must be disabled even if the student is not in exam mode

**Comment by M4xi1m3** [comment]
Instead of country specific stuff, we could, after the Lang select, make a menu for things like that (like "does your country allows symbolic calculation : yes/no")

**Comment by quentinguidee** [comment]
Deprecated
