### ISSUE TITLE
Buggy white pixels in External

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#141]
#### Describe the bug
If you turn the calculator off and on in External, a line of buggy pixels appears.

#### Environment
 - Omega Version: 1.18.4
 - Model : n0100

**Comment by RedGl0w** [comment]
I think this is due to the fact there was no row in the table. Since my PR it's done...
This issue appears also on RPN (without any thing in the stack)

**Comment by quentinguidee** [comment]
The buggy white pixels don't appear anymore on 1.19 (because of #140). Feel free to reopen!
