### ISSUE TITLE
Bugged "Activate exam mode" stays highlighted

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#142]
#### Describe the bug
By selecting the activation of the examination mode, then by canceling, the button "Activate exam mode" remains dark (instead of white).

![Capture](https://user-images.githubusercontent.com/52292872/72088751-1c428600-330b-11ea-946a-26b4409391ac.PNG)

#### Environment
 - Omega Version: 1.18.4
 - Model : n0100

**Comment by quentinguidee** [comment]
Thanks! Fixed by #150 ;)
