### ISSUE TITLE
Differentiate developers and beta testers in "Contributors"

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#144]
#### What I want to see in the next version of Omega

I propose to differentiate in "Contributors" the developers in red and the beta testers in blue.
Or when you press "OK" on a name, the mention "Developer/Beta Tester" appears.

(For example)

**Comment by quentinguidee** [comment]
Closed with d8cc958cf5464a34bbb0211828aeccd580b97e67

Thank you for the issue!
