### ISSUE TITLE
Problem with shift + clear in Python shell

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#149]
#### Describe the bug
If I once shift + clear in Python Shell to erase part of a word, then I redo shift + clear, the rest is "erased" but does not disappear.

![1](https://user-images.githubusercontent.com/52292872/72174218-7873db80-33d9-11ea-92e5-a462c9a2d12e.png)
![2](https://user-images.githubusercontent.com/52292872/72174226-79a50880-33d9-11ea-99cd-3da1fbbd2d24.png)
![3](https://user-images.githubusercontent.com/52292872/72174238-7f025300-33d9-11ea-8d14-d19619492ebc.png)

#### Environment
 - Omega Version: 1.18.4

**Comment by RedGl0w** [comment]
Already reported
I asked also @boricj , because he had the same issue on RPN...

**Comment by boricj** [comment]
Probably a bug in the rect invalidation code, but that's not Omega-specific. File an issue upstream.

**Comment by A2drien** [comment]
It's done. https://github.com/numworks/epsilon/issues/1272

**Comment by quentinguidee** [comment]
I close this bug since it also appears upstream.
