### ISSUE TITLE
RPN Mode

### ISSUE THREAD

**Issue by RedGl0w** [Omega-Numworks/Omega#15]
#### What I want to see in the next version of Omega
I think for the rpm mode you could ask for permission to boricj for his rpn app which works quite perfectly
https://github.com/boricj/numworks-rpn

**Comment by quentinguidee** [comment]
https://github.com/boricj/numworks-rpn/issues/12

**Comment by quentinguidee** [comment]
I imported **boricj/numworks-rpn** as a submodule on github (see [here](https://github.com/Omega-Numworks/Omega/tree/lavaos/apps))

Don't forget clone it.

It's not yet implemented (because it crashes on this version) but it's here!

**Comment by quentinguidee** [comment]
https://github.com/Omega-Numworks/Omega-RPN/issues/1

**Comment by quentinguidee** [comment]
Done! Thanks to **boricj** for this app! cf39a06
