### ISSUE TITLE
Time lib bug

### ISSUE THREAD

**Issue by LeGmask** [Omega-Numworks/Omega#156]
#### Describe the bug

The times lib in py has some bug :

- [ ] sleep() just froze the screen and nothing is possible to do like print or draw on screen ....

- [x] ~~monotonic do nothing~~

- [ ] The lib just make the n0100 crash 1/2 times

#### Environment
- n0100 only for crash
 - Omega Version: 18.idk

**Comment by RedGl0w** [comment]
For the `sleep()` issue, it's normal : the `sleep()` puts the calculator in sleep mode. If you want to continue the script, until x second, stock in a var the return of `monotonic()`, and compares it to `monotonic()`.
For the lib issue, that comes from upstream, so you can close this issue.

**Comment by quentinguidee** [comment]
I close this issue, feel free to reopen it

**Comment by RedGl0w** [comment]
And I checked it doesn't crash, but when you use `sleep()`, the calculator doesn't react anymore.
