### ISSUE TITLE
Bigger toolbox

### ISSUE THREAD

**Issue by arthur062318** [Omega-Numworks/Omega#157]
#### What I want to see in the next version of Omega

As there are more and more stuff in the toolbox, I think it would be better for the pop-up menu to take more space on the screen, especially when we are scrolling to the bottom of the list.

Thanks.

**Comment by quentinguidee** [comment]
Hello @arthur062318 !

I tried to implement your idea, but despite that it looked good, I don't think it's very beautiful... I let you a screen.

<img width="432" alt="Capture_decran_2020-01-23_a_22 31 28" src="https://user-images.githubusercontent.com/12123721/73040220-0d0a1f00-3e59-11ea-86e1-e844224bebc3.png">

So, I don't think we'll implement this feature, so I'll close the issue.However, if you have a better idea to see more elements in the toolbox, feel free to reopen :)

Thanks!
