### ISSUE TITLE
Matrix multiplying or dividing return undef

### ISSUE THREAD

**Issue by NodeNXT** [Omega-Numworks/Omega#158]
#### Describe the bug
When I multiply or divide two matrix, the result is undef. For example [2, 2]*[2, 2] returns undef.

#### Environment
Omega Version: 1.18.4-0
Epsilon Version: 12.0.0
μPython Version: 1.11.0

**Comment by quentinguidee** [comment]
These are two column matrices?

**Comment by NodeNXT** [comment]
Down below is what I type. And above it is the result :
https://cdn.discordapp.com/attachments/276813132901384192/665568249236291605/Snapchat-2034353471.jpg

**Comment by quentinguidee** [comment]
Yes it's totally normal 😉 It's undef

Iff you have two matrices, their size must be i * j and j * k (so j must be the same). Here you make 1*2 and 1*2. So you cannot multiply them. It don't work like vectors 😉 

See here how to multiply two matrices : https://www.mathwarehouse.com/algebra/matrix/multiply-matrix.php

You'll see your two matrices can't me multiplied... It's like dividing by 0

Nevertheless, thank you anyway for taking the time to open this issue 😉 If you really think it's a bug don't hesitate to reopen 😉

**Comment by quentinguidee** [comment]
You can try [2 2] and (in column) [2 2] it will work ;)

**Comment by NodeNXT** [comment]
Okay, I'm just stupid :')

**Comment by quentinguidee** [comment]
Ahah don't worry, we've all been there 😂
