### ISSUE TITLE
Python: key map in modkandinsky incorrect

### ISSUE THREAD

**Issue by KaiJan57** [Omega-Numworks/Omega#162]
#### Describe the bug
https://github.com/Omega-Numworks/Omega/blob/a08a46d62fdfd5e129026a501abb950c59b0962e/python/port/mod/kandinsky/modkandinsky.cpp#L117-L119
Right maps to up and vice versa; so it should be the other way around.

#### Environment
 - Omega Version: 1.18.4

**Comment by quentinguidee** [comment]
Hi! thanks for this bug report! Thanks to you, it will be fixed in Omega 1.19, since we merged #167 😉
