### ISSUE TITLE
Cursor bug in RPN

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#163]
#### Describe the bug
If you select the first or second line when the 8 lines are used, the cursor duplicates on the next line.

![screenshot (3)](https://user-images.githubusercontent.com/52292872/72266624-0d1b4b00-361f-11ea-976f-5d62a586ad57.png)
![Capture1](https://user-images.githubusercontent.com/52292872/72267125-d265e280-361f-11ea-8c75-03c52383982b.PNG)

#### Environment
 - Omega Version: 1.18.4

**Comment by quentinguidee** [comment]
Thank you for reporting this bug!

But unfortunately, we're not in charge of the RPN development.. Can you send this bug in https://github.com/boricj/numworks-rpn ?

Thank you!

**Comment by A2drien** [comment]
It's done. https://github.com/boricj/numworks-rpn/issues/21

**Comment by quentinguidee** [comment]
Thanks! :)
