### ISSUE TITLE
[n0100] LED Blinking speed fluctuates when calculator used

### ISSUE THREAD

**Issue by ifndev** [Omega-Numworks/Omega#165]
#### Describe the bug
The LED blinking pattern fluctuates when you use the keyboard/plot graphs/whatever needs a tiny bit of processing

[example](https://youtu.be/Xlha1hzjyM0) (sorry for the background music)

#### Environment
 - Omega Version: 1.18.4-0
 - Installed from: Official binaries - web installer
 - Model: n0100

EDIT: This is a problem that also concerns official firmware but it doesn't seem to by fixed for now. [issue open on numworks/epsilon](https://github.com/numworks/epsilon/issues/1273)

**Comment by quentinguidee** [comment]
Hi @ifndev ! Thank you for the issue :)

But unfortunately, since this issue also appears on Epsilon, we'll not fix it on Omega. But if someone fix it on Epsilon, we'll merge the bug fix !

Thank you ;)
