### ISSUE TITLE
Add some math and physics formulas

### ISSUE THREAD

**Issue by NodeNXT** [Omega-Numworks/Omega#172]
#### What I want to see in the next version of Omega
It would be really cool if you add math formulas to the toolbar like remarkable identities (a ^ 2 - b ^ 2, (a -b) ^ 2, etc ...) or physics formulas like this Newton's gravitation or the formula to calculate the molar mass (m = M * n) with of course the units that go with each letter

**Comment by quentinguidee** [comment]
Hi! Thanks for this issue 😉

We discussed it a lot, but unfortunately, we think:
* It will cause problems with the exam mode
* There aren't enough interesting formulas to add... The remarkable identity can be achieved using the symbolic calculation of the calculation app; and m=Mn can be found with the units.

And also, in my opinion, it is smarter to try to find or learn them than to put the formula as it is.

So, we don't want to take the risk :/

Feel free to reopen if you have other ideas related to this issue

Thanks :)
