### ISSUE TITLE
Shift + up and shift + down shortcut

### ISSUE THREAD

**Issue by M4xi1m3** [Omega-Numworks/Omega#177]
#### What I want to see in the next version of Omega

Could we make sure that shift + "up arrow" leads to the beginning of the script in the Python editor and to the first value in a list in the statistics menu (useful when you have to enter the numbers after entering the values, especially if the list is long) ? Similarly, shift + "down arrow" could lead to the end of the script or to the last value in the list.

(thanks to telpe51#3016 for the idea)

**Comment by quentinguidee** [comment]
Closed with #191
