### ISSUE TITLE
Propose an exam mode by country

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#184]
#### What I want to see in the next version of Omega
In 1.18.5, we have 3 different exam modes.
I propose to do 1 personalized exam mode per country, so that the user is sure of what he should select.

(In 1.18.5 : )
![screenshot (9)](https://user-images.githubusercontent.com/52292872/72742778-b4155f00-3baa-11ea-8c01-f5dc067fd1c3.png)

**Comment by quentinguidee** [comment]
Hi @A2drien ! Thank you for this issue!

Since Omega 1.19, we decided to make exam modes by functionalities, because of the regulations. So I'll close this issue. Feel free to comment
