### ISSUE TITLE
Translate ForbidenAppInExamMode1 and ForbidenAppInExamMode2 message in all languages

### ISSUE THREAD

**Issue by citorva** [Omega-Numworks/Omega#185]
When we are using the dutch examination mode, python application is forbidden and the error message is always in English even with other translation.

Follow pictures of this dialog in each unsupported languages:
![de](https://user-images.githubusercontent.com/16229435/72750720-e2506a00-3bbd-11ea-94c2-a1b3d6a78289.jpg)
![es](https://user-images.githubusercontent.com/16229435/72750721-e2506a00-3bbd-11ea-8a55-35741f40dc34.jpg)
![fr](https://user-images.githubusercontent.com/16229435/72750723-e2506a00-3bbd-11ea-866f-e54fe7b41ae4.jpg)
![pt](https://user-images.githubusercontent.com/16229435/72750726-e2e90080-3bbd-11ea-8df1-81ceff4a7b0e.jpg)

Note: currently, only python program in the Dutch/No algebra examination mode is locked. Actually, French, Spanish, Portuguese and German spoken students may not see this message but, it will be useful to implement translation in these languages if an official application that can not be used in any examination mode is added to the firmware.

**Comment by quentinguidee** [comment]
Thanks for this issue! Since the Dutch mode is made by Epsilon, I think they'll translate themselves. But at this time we don't know. So, if they don't translate the popup with the official release of Epsilon 13, we'll translate this in Omega.

For the moment, I'll put the "On Hold" tag. We'll see what Epsilon do :)

**Comment by quentinguidee** [comment]
Thanks! This issue seems to be fixed in Epsilon 14.4.1 ^^
