### ISSUE TITLE
Add all contributors 

### ISSUE THREAD

**Issue by RedGl0w** [Omega-Numworks/Omega#186]
Add the all contributors bot to the reporistories of omega, to 
https://allcontributors.org/docs/en/bot/installation

**Comment by quentinguidee** [comment]
I tried it, but it pushes in the wrong branch. So, I did this manually
![Omega-Contributors](https://user-images.githubusercontent.com/12123721/73199059-6f527080-4134-11ea-9e40-46f61fbe2be9.png)
