### ISSUE TITLE
graphical bug in rpn app

### ISSUE THREAD

**Issue by windows9x95** [Omega-Numworks/Omega#188]
Hi,
I found a bug in omega rpn app this happen when we turn off the calculator without any
data entered in rpn app and then power on
there will be a multicolor bar 
This is green because I use a theme :)

 - Omega Version: 1.19.0-0 dev
if the quality isn't good this is because Imade this issue on my phone

**Comment by RedGl0w** [comment]
This comes from escher
We had the same issue with externals on n0100

**Comment by A2drien** [comment]
This has already been reported : https://github.com/Omega-Numworks/Omega/issues/141

**Comment by quentinguidee** [comment]
@A2drien Yes! (but closed because it was about External (patched) )

Thanks for reporting this issue!

**Comment by quentinguidee** [comment]
I just think this issue must be send to @boricj, because we don't develop RPN (https://github.com/boricj/numworks-rpn)

I'll close the issue because of this, but feel free to reopen! :)

Thanks!
