### ISSUE TITLE
syntax error with 10 power

### ISSUE THREAD

**Issue by windows9x95** [Omega-Numworks/Omega#190]
Hi,
I found a calculation bug in Omega dev 1.19.0-0 who isn't present in Omega release 1.18.5-0, this is when we calculate the power of 10 ("puissance de 10" in french, I don't know the English of that), the calculator send syntax error. this wasn't in the previous version.

**Comment by Math07170** [comment]
Hi, How do you make this bug I have the lastest version of Omega and there is no problem with the power of ten or "puissances de 10" ?

**Comment by windows9x95** [comment]
Yes now it's working but today when I was doing chemical in class I was calculating with the power of ten for some atom weight  and the calculator send me this error, with the calculator of a friend (omega 1.18.5-0) it was working

**Comment by MixedMatched** [comment]
I suspect this has to do with #152. @RedGl0w.

**Comment by RedGl0w** [comment]
I checked and my PR's working fine

**Comment by windows9x95** [comment]
I retried it a few time, and this work fine, but I always don't know why this wasn't working in my chemical class...

**Comment by quentinguidee** [comment]
I close this for the moment, since the bug doesn't appear anymore
