### ISSUE TITLE
Improve behavior of root key

### ISSUE THREAD

**Issue by Lelahelry** [Omega-Numworks/Omega#193]
#### What I want to see in the next version of Omega
Use the same "character" as the root(x,n) function in the toolbox upon pressing the root key. Enables users to do other roots other than squared more easily, all the while not adding ay complexity since the default behavior of this fuction is squared root.

BTW, I just figured you could do the same thing with the log key and log(x,a) function. Might be cool to add a setting for that aswell.

**Comment by quentinguidee** [comment]
Good idea! But I would consider doing a setting for that (in "Math options"), because the blue square is always here and may be not user-friendly, because people will think that they must enter a number.

**Comment by Lelahelry** [comment]
Yeah a setting is totally fine I think!

**Comment by Lelahelry** [comment]
BTW, I just figured you could do the same thing with the log key and log(x,a) function. Might be cool to add a setting for that aswell.

**Comment by LeGmask** [comment]
Fixed by #290 ! You can close this issue !
