### ISSUE TITLE
Put a clock at the title bar

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#197]
#### What I want to see in the next version of Omega
A default option disabled. When activated, it requests an hour, and the HSE clock will run continuously from this moment until the option is deactivated.

**Comment by RedGl0w** [comment]
Cf. https://github.com/numworks/epsilon/pull/311
H's working on a new version

**Comment by quentinguidee** [comment]
Thank you for this issue! Done by @boricj with #347 and will be available in Omega 1.21 :)
