### ISSUE TITLE
Be able to select the text to copy in the Python editor.

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#203]
#### What I want to see in the next version of Omega
Idea from @telpe51 (on Omega's Discord)
Shift + var (copy) does not allow you to copy a text precisely, so I suggest to be able to select the text to copy in the Python editor.

**Comment by M4xi1m3** [comment]
Maybe alphalock + arrows could work? Or having a custom key combination for select and then arrows?

**Comment by RedGl0w** [comment]
This is patched since E13
