### ISSUE TITLE
N0100 : Put the LED in orange or green during charging

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#204]
#### What I want to see in the next version of Omega
N0100 : Light the LED in orange while charging, and in green if the calculator is charged. (as for N0110)

**Comment by M4xi1m3** [comment]
On n0110, this is already the case (orange when charging, green when charged)

**Comment by quentinguidee** [comment]
I close the issue, since it already exists on n0100 and n0110

**Comment by M4xi1m3** [comment]
This is more of a bug than a feature request. I think this should be reported on epsilon, as it's a bit which is present there too and is easily fixable.

**Comment by quentinguidee** [comment]
https://github.com/numworks/epsilon/issues/1284#issuecomment-579799455

According to Numworks,
> Great suggestion, but unfortunately this is something the hardware won't let us do properly.

So I'll close the issue ; thank you for the suggestion!
