### ISSUE TITLE
Shift + "÷" make "%"

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#205]
#### Describe the bug
Shift + "÷" make "%" (instead none).

#### Environment
 - Omega Version: 1.18.5

**Comment by RedGl0w** [comment]
This comes from [here](https://github.com/Omega-Numworks/Omega/commit/3e91ba0f80895afa5ba19f32f4eafdcc0fdf6703#diff-800a8b256de0a3da954212e544241a67)
I'll PR to fix it

**Comment by quentinguidee** [comment]
Closed by #222 

Thanks for this issue!
