### ISSUE TITLE
Bug in x * number ^ power

### ISSUE THREAD

**Issue by mouzg** [Omega-Numworks/Omega#210]
#### Describe the bug
Shift + "÷" make "%" (instead none).

if i enter X*1234.5^power it works as it should, but at the moment i enter the same expression again without the * sign X1234.5^power it transforms it to X1234 * 0.5^power.This happens in calculation and equations menu. (Omega version is 1.18.5-0 - Epsilon version 12.0.0). [Edit]. It is an Epsilon bug (tried it on online simulator Epsilon version 12.3.8)  should i post it there?

#### Screenshot

![screenshot](https://user-images.githubusercontent.com/29000307/73205724-44731700-414a-11ea-8de5-944bbc3d75bc.png)

#### Environment
 - Omega Version: 1.18.5

**Comment by quentinguidee** [comment]
Really strange... Thank you for reporting this bug! If this bug also appears on the Epsilon simulator, you should, as you said, send this bug upstream. We avoid fixing bugs in Omega that come from Epsilon.

Thank you again for this issue. I close it, since we'll not fix it in Omega. Feel free to comment if you want to reopen it.

**Comment by mouzg** [comment]
Thank you for your time. Can i ask you didn't it seem to you as a bug ? Im asking because i posted it in epsilon's git and nobody is answering at it for days.
________________________________

**Comment by quentinguidee** [comment]
Don’t worry, for the moment I think Epsilon doesn’t have enough time to answer directly; they’re busy with the next version of Epsilon. So, if you check the other recent issues on Epsilon, you’ll see that nobody gets answers.  So don’t worry, it’s normal. However, if they close the issue (even if I don’t fink they will), we’ll look ourselves at this issue.

Don’t hesitate to comment if you have any news on this 😉 Thanks!

**Comment by nsajko** [comment]
This is not actually a bug: the misunderstanding arises from the fact that in math classes identifiers of variables are usually single letters. But one may want an indentifier/variable name to be longer than a single letter, and also to potentially include numbers. This is what is happening here: when Epsilon sees `x1234`, it knows that is (part of) a variable name, then the `.` comes, thus the variable name has come to an end, and what follows (`.5`) is a literal number - 0.5, which is implicitly multiplied with the variable `x1234`.

(This is called "lexing", or, more widely, "parsing".)
