### ISSUE TITLE
Alpha + Delete (locked) cannot clear history

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#218]
#### Describe the bug
If you do alpha + Delete (locked), it cannot delete history in Calculation and Python shell (one by one).
I am talking about erasing only a calculation or a console line on the console, not erasing the entire history.

#### Environment
 - Omega Version: 1.18.5

**Comment by quentinguidee** [comment]
Hi! Does this bug happen again on Epsilon?

**Comment by A2drien** [comment]
It's not a bug on Epsilon : alpha + Delete (locked) made "%" x)

**Comment by quentinguidee** [comment]
That is what I thought! Thanks for the issue :) !

**Comment by A2drien** [comment]
This problem is gone with E14.4.0 and O1.20.
