### ISSUE TITLE
Led stop bliking when powered off on n0110

### ISSUE THREAD

**Issue by RedGl0w** [Omega-Numworks/Omega#22]
#### Describe the bug
When you change LED color and you go to exam mode, and then you power off you calculator, the led stops blinking, whereas on epsilon 12.0.0 it continues...

#### Environment
 - Omega Version : 1.9.0
- Model : n0110

**Comment by M4xi1m3** [comment]
Tried it, I can confirm. Also, it doesn't start blinking again when you turn the calculator back on.

**Comment by M4xi1m3** [comment]
I found where the issue is. I'll open a PR when I'm done fixing it.
