### ISSUE TITLE
How to upload python scripts to Numworks?

### ISSUE THREAD

**Issue by OrnithOrtion** [Omega-Numworks/Omega#221]
Hi,
I just installed **Omega** on my numworks calculator to get the periodic table and the physics constants (and I see that there are other nice functions ...).

Is there any other method than the numworks workshop to write python programs on a computer and then upload them to the calculator?

Thank you for this very useful version,
thank you in advance for your help !

Samuel ORTION
Lycée Terminale S, Lycée Notre-Dame, Le Mans, 72.

---

Salut,
Je viens d'installer **Omega** sur ma calculatrice numworks pour obtenir le tableau périodique et les constantes de physique( et je vois qu'il y a d'autres fonctions sympa... ).

Est-ce qu'il y a une autre méthode que le workshop de numworks pour écrire des programmes python sur un ordinateur pour ensuite les téléverser sur la calculette ? 

Merci pour cette version très utile,
merci d'avance pour votre aide ! 

Samuel ORTION
Lycéen Terminale S, Lycée Notre-Dame, Le Mans, 72.

**Comment by RedGl0w** [comment]
WoW
I live in Le Mans too
(Lycée Montesquieu)

**Comment by quentinguidee** [comment]
Hi @OrnithOrtion ! Thank you for reporting this issue! Can you say the version of Omega you use? You can see it in the settings > about > Omega version. Thank you!

---

Hello @OrnithOrtion ! Merci d'avoir reporté ce problème! Pouvez-vous dire quelle version d'Omega vous utilisez ? Vous la trouverez dans paramètres > à propos > version d'Omega. Merci !

**Comment by OrnithOrtion** [comment]
Je me suis mal exprimé, le workshop fonctionne bien. Je me demandais juste si il y avait une autre méthode...

(Epsilon version 12.0.0
omega version 1.18.5-0)

**Comment by quentinguidee** [comment]
Ah ok! For the moment no, we have no alternative, but we are thinking about it! If you have any questions or suggestions, you can come to our Discord to talk about them ;)

---

Ah ok! Pour le moment non nous n'avons pas d'alternative, mais on y réfléchit! Si tu as des questions ou suggestions, tu peux venir sur notre Discord pour en parler ;)

**Comment by M4xi1m3** [comment]
A custom workshop-like software is discussed on discord. We will start working on it once the redesign of the website is done. If you have any interesting ideas, you can  come talk with us on the discord https://discord.gg/nCaNTkx.
<hr/>

Un logiciel custom type-workshop est discuté actuellement sur le discord. On attends juste que le redesign du site web soit terminé. Si tu as des idées tu peux venir en parler sur le discord https://discord.gg/nCaNTkx.

**Comment by quentinguidee** [comment]
I close the issue. Please comment if you want to reopen it. Thanks!
