### ISSUE TITLE
Custom LED Color

### ISSUE THREAD

**Issue by NodeNXT** [Omega-Numworks/Omega#223]
#### What I want to see in the next version of Omega
Add a custom LED color for exam mode with color selection in RGB. UI example : 
![Background](https://user-images.githubusercontent.com/54221049/73615516-d9718680-4608-11ea-86ac-316f24dd5172.png)

**Comment by quentinguidee** [comment]
Thanks for this issue! We'll think about it!

(#66)

**Comment by quentinguidee** [comment]
Since #390 we decided to remove the led choice. This issue is now deprecated.
