### ISSUE TITLE
Data app

### ISSUE THREAD

**Issue by arthur062318** [Omega-Numworks/Omega#224]
## Introduction

I definitely think representing data is essential in sciences, but unfortunately that's very hard on calculators. NumWorks tried to improve the situation by adding an histogram in the "Statistics" app, but that is quite specific and therefore not as useful as it could be.

I would like to have a more complete tool for any kind of data (not just statistics), with a table to enter/edit data and several models to represent it, all of this in my calculator.

## Table

The table is an essential part of the app, because that's the best way to enter and edit data.

In some cases, it can be interesting to enter multiples informations for each element of the data set, so this table have to manage more than only 2 columns of data.

## Charts

Here are the most important charts to implement (to me) :

- histograms
- line charts
- scatter plots

If there are more than 2 columns of information, the user might choose wether the values from the diffferents columns of data are stacked or not in the chart view.

## Trendline

The user might want to model the trend of a data set, searching for a specific form of trendline equation.

### Equation

- Linear
- Polynomial
- Logarithmic
- Exponential
- Moving average
- Powers

### Tools

The user might want to :

- access the equation
- send the equation to the "Functions" app
- obtain the correlation coefficient

## Conclusion

I know it looks like a big task but I'm sure such an app would make perfect sense for many of us.

Thanks for everything.

**Comment by arthur062318** [comment]
Well I just discovered the "Regression" app. 🙈 
I should close the issue before anyone notifying.

But there are still some improvements :
- correlation coefficient
- send the equation to the "Functions" app

**Comment by quentinguidee** [comment]
Wow thank you for this very detailed issue 😎 You discovered the regression app just 5 seconds too late 😟

If you want these 2 minor changes, could you post them in two separate issues? Thank you very much!! And again, thank you for this very detailed issue, even if it’s already implemented :’(

**Comment by quentinguidee** [comment]
Feel free to comment if you want to reopen this issue!
