### ISSUE TITLE
Problem with parenthese in python app

### ISSUE THREAD

**Issue by windows9x95** [Omega-Numworks/Omega#226]
#### Describe the bug
When I try to do a parenthese with shift + left parenthese, in the python app, the cursor go after the parenthese, but in the calculation app, the cursor go between the parenthèses, I don't know if this is a bug or not. I send a link for a video who show what happen in the python app

#### Environment
 - Omega Version: 1.19.0-0 d8cc958

video where we see what happen in the python app : https://drive.google.com/file/d/1DZuzAXH8AekAP2id6W61G38IUF0xIo_l/view?usp=drivesdk

**Comment by RedGl0w** [comment]
We need to add the special character for forcing the cursor position

**Comment by quentinguidee** [comment]
Closed with #228
