### ISSUE TITLE
Stuck during flash

### ISSUE THREAD

**Issue by Drasnore** [Omega-Numworks/Omega#227]
Hello, my n0110 don't seem to be recognized by msys2, since after following the instructions on the terminal nothing happens

# make epsilon_flash
DFUSE   epsilon.dfu
CXX     ion/src/device/shared/usb/dfu_xip.o
CXX     ion/src/device/flasher/main.o
CXX     ion/src/device/flasher/display_light.o
LD      flasher.light.elf
DFUSE   flasher.light.dfu
DFU     epsilon_flash
INFO    About to flash your device. Please plug your device to your computer
        using an USB cable and press at the same time the 6 key and the RESET
        button on the back of your device.

**Comment by Gegenter** [comment]
Hey, thanks for letting us know! Does it work with the web installer? https://omega-numworks.github.io/install.html  so you are on Windows right?

**Comment by Drasnore** [comment]
YES THANKS!!
But I'm still wondering why it doesn't pickup the calculator, I did all the steps on your website but still stuck at the same step as before.
Also it was stuck on "waiting for reconnection" on the web installer of Omega, but I unplugged it since it was almost 5 minutes that it was stuck.

**Comment by Gegenter** [comment]
Yeah the web installer is still buggy, but we are working on it. Still thats weird that the web installer can connect to your calculator but msys2 cannot... Let's wait for someone smarter than me to join the conversation, until then, you could join the discord! It's probably faster that way

**Comment by RedGl0w** [comment]
Do you have the numworks' windows driver (from the workshop) ?

**Comment by Drasnore** [comment]
Yes, but since I used zadig this is what show up in the peripheral manager.
![Capture d’écran (66)](https://user-images.githubusercontent.com/48979959/74102290-8042af00-4b42-11ea-8fac-fbdfd8dc72a1.png)

**Comment by RedGl0w** [comment]
can you try `lsusb -v` ?

**Comment by Drasnore** [comment]
It says command not found

**Comment by RedGl0w** [comment]
Can you try `dmesg | grep NumWorks`

**Comment by Drasnore** [comment]
same thing
# dmesg | grep NumWorks
-bash: dmesg : command not found

**Comment by Drasnore** [comment]
ok so it appears that the epsilon.elf is not created after the make command, but I can't find it anywhere so I'm going to redownload the epsilon git repo

**Comment by quentinguidee** [comment]
Hi @Drasnore !
Is this issue fixed ?

**Comment by Drasnore** [comment]
Well sort of, I went to install a Virtual Machine with Linux and that solved all my problems

**Comment by quentinguidee** [comment]
Okay perfect! :)
