### ISSUE TITLE
keyboard sqrt improvement

### ISSUE THREAD

**Issue by LeGmask** [Omega-Numworks/Omega#230]
#### What I want to see in the next version of Omega
---------------------------------------------------------

- [ ] Change the sqrt key of the keyboard by the toolbox one

**Comment by Lelahelry** [comment]
I've already opened an issue for the same feature.

**Comment by quentinguidee** [comment]
Duplication of #193 :/

Thank you for the issue!

**Comment by LeGmask** [comment]
ah sorry so :-), Because i've started ...

**Comment by quentinguidee** [comment]
Don't worry!
