### ISSUE TITLE
To be able to convert time period and frequency to distance

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#232]
#### What I want to see in the next version of Omega
The unit converter is great, but it is impossible to convert units of distance to frequency and time and vice versa.

There is the formula λ = v / f and λ = v × T, with λ which is the length of wave, v which is the speed of light (c for the French) (= 3.00 × 10**8), f which is the frequency of the wave and T which is the time period (in seconds).

"What we type on the calculator" = "Result returned" (= which corresponds to)
(distance λ)_m➔_Hz = (3.00 × 108 / distance λ) _Hz (= frequency f)
(frequency f)_Hz➔_m = (3.00 × 108 / frequency f) _m (= distance λ)
(distance λ)_m➔_s = (distance λ / 3.00 × 108) _s (= time period T)
(time period T)_s➔_m = (3.00 × 108 × time period T)_m (= distance λ)

**Comment by quentinguidee** [comment]
I think it’s more a formula, not really an unit conversion. As said upstream, the constant of proportionality between λ and 1/f is not always v=c=10^8 :/

I close this for the moment, feel free to comment if you want to reopen!
