### ISSUE TITLE
Which physic constant would you like to see ?

### ISSUE THREAD

**Issue by RedGl0w** [Omega-Numworks/Omega#24]
#  Unit of measurement :

- [x] Speed of light in m/s

- [x] One light year in km

# Thermodynamics

- [x] Boltzmann constant : k_b = 1.38064852.10⁻²³ J.K⁻¹

- [x] Avogadro constant : N_A = 6.02214076.10²³ mol⁻¹

- [x] Gas constant : R = 8.31446261815324 kJ.K⁻¹.mol⁻¹

- [x] Weight of an electron

- [x] Weight of an proton

- [x] Weight of an neutron

# Electromagnetism

- [x] Coulomb constant : k_0 = 8.9875517887.10⁹ N.m².C⁻²

- [x] Vacuum permittivity : ε_0 = 8.8541878128.10⁻¹².F.m⁻¹

- [x] Vacuum permeability : μ_0 = 4π.10⁻⁷ T.m.A⁻¹

- [x] Planck constant : h = 6.62607015.10⁻³⁴ m².kg.s⁻¹

- [x] Elemental charge: e = 1,60217662E-19 C

# Gravitation

- [x] Gravitational acceleration: g_0 = 9,80665 m.s⁻²
- [x] Gravitational constant: G = 6.674E-11 m³.kg⁻¹.s⁻²

Please comment this issue with idea of physics constants to be added to omega !
Thanks

**Comment by quentinguidee** [comment]
**Thermodynamics**
- [x] Boltzmann constant : k_b = 1.38064852.10⁻²³ J.K⁻¹
- [x] Avogadro constant : N_A = 6.02214076.10²³ mol⁻¹
- [x] Gas constant : R = 8.31446261815324 kJ.K⁻¹.mol⁻¹

**Electromagnetism**
- [x] Coulomb constant : k_0 = 8.987551788.7 N.m².C⁻²
- [x] Vacuum permittivity : ε_0 = 8.8541878128.10⁻¹².F.m⁻¹
- [x] Vacuum permeability : μ_0 = 4π.10⁻⁷ T.m.A⁻¹
- [x] Planck constant : h = 6.62607015.10⁻³⁴ m².kg.s⁻¹

**Comment by RedGl0w** [comment]
Merge request opened
https://github.com/Omega-Numworks/Omega/pull/31

If you have any other, don't hesitate to comment !

**Comment by M4xi1m3** [comment]
Electromagnetism :

- [ ] Elemental charge: e⁻ = 1,60217662E-19 C

Gravitation :

- [ ] Gravitational acceleration: g_0 = 9,80665 m.s⁻²
- [ ] Gravitational constant: G = 6.674E-11 m³.kg⁻¹.s⁻²
