### ISSUE TITLE
Polar/parametric function in functions app cause crashes

### ISSUE THREAD

**Issue by MixedMatched** [Omega-Numworks/Omega#25]
#### Describe the bug
After graphing a parametric or polar function, if you try to press on the table button, the entire calculator crashes and must be reflashed.

#### Environment
 - Omega Version: 1.9.0-0
 - Model: n0100

**Comment by MixedMatched** [comment]
Upon further testing, it only happens when a polar or parametric is the first function.

**Comment by M4xi1m3** [comment]
Confirmed to work on simulator and on n0110. https://pastebin.com/BHv9g3Bu

**Comment by MixedMatched** [comment]
These errors happen on mainline epsilon. Transferring to upstream https://github.com/numworks/epsilon/issues/1188.
