### ISSUE TITLE
Change LED color while exam mode is on

### ISSUE THREAD

**Issue by NodeNXT** [Omega-Numworks/Omega#253]
When the exam mode is active we can't change the LED color. I don't know is wanted but, it will be cool !

#### Environment
 - Omega Version: 1.19.0-0

**Comment by LeGmask** [comment]
I don't think this idea is possible, because changing color led may create issue with examinator, and for some special exam mode it isn't possible, the led color must be fixed.

**Comment by quentinguidee** [comment]
Hello! With #390, we decide to completely remove the leds choice. So this issue is now deprecated.
