### ISSUE TITLE
Add a unit to the physics constants.

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#256]
#### What I want to see in the next version of Omega
Modify the physics constants so that they integrate the corresponding unit of measurement.
For example, c = 3 × 10 ^ 8 => c = 3 × 10 ^ 8 m/s

Idea from @parisseb : https://tiplanet.org/forum/viewtopic.php?f=97&t=23517&p=251481#p251475

**Comment by quentinguidee** [comment]
Done by #278 !
