### ISSUE TITLE
Battery Percentage

### ISSUE THREAD

**Issue by fin1taylor** [Omega-Numworks/Omega#259]
#### What I want to see in the next version of Omega
Add an option to display the battery percentage at the top next to the battery icon.

**Comment by 0Babass2** [comment]
It isn't possible because the voltmeter is not sufficiently precise.

**Comment by quentinguidee** [comment]
Thank you for this issue! Unfortunately, the battery percentage is really unreliable :/ so I close the issue for now. Feel free to comment if you want to reopen this issue!

Thanks!
