### ISSUE TITLE
Setup script

### ISSUE THREAD

**Issue by quentinguidee** [Omega-Numworks/Omega#26]
#### What I want to see in the next version of Omega
Make a script (something like "install.sh") that will:
- install dependencies
- ask for apps we want to include
- ask for language we want
- ask the model (n0100/n0110/simulator/...)
- make clean
- make
- ask the user to do some manipulations
- make app_flash
- make epsilon_flash

**Comment by MixedMatched** [comment]
It should be in python to run on all platforms.

**Comment by quentinguidee** [comment]
I made a new repo [here](https://github.com/Omega-Numworks/Omega-CLI-Installer) with the python script. The installer don't handle errors at this time, and don't install dependencies. I only tried it on linux (arch/manjaro). I didn't post the python script on this main repository because i want it to be more flexible in the future (eg. choose the version of Omega we want to install). So, the script clone this main repository during the process.
