### ISSUE TITLE
Compile in official

### ISSUE THREAD

**Issue by LeGmask** [Omega-Numworks/Omega#266]
#### Describe the bug

Compile in official crash
![image](https://user-images.githubusercontent.com/53308142/74960598-eb2a9a80-540c-11ea-8008-a199814b7dc3.png)

#### Environment
 - Omega Version: 1.20

**Comment by quentinguidee** [comment]
Thank you for the issue! Now fixed with f1e39b6709fd3528706a35cd72c46eb389f654f2
