### ISSUE TITLE
Rename the simulator

### ISSUE THREAD

**Issue by quentinguidee** [Omega-Numworks/Omega#270]
#### What I want to see in the next version of Omega
The simulator renamed (Epsilon -> Omega)

**Comment by RedGl0w** [comment]
This is on all the simulators (mobile, emscripten and linux/Windows)

**Comment by quentinguidee** [comment]
- [x] Web and simulator : 4d8a6488c4622056478b758a651ac15a7a354f39
- [ ] Android simulator : #271
- [ ] Windows simulator

**Comment by quentinguidee** [comment]
Omega 1.20+
