### ISSUE TITLE
Add the Omega theme to hardware test

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#288]
#### Describe the bug
The hardware test buttons don't have the Omega theme.

![screenshot (11)](https://user-images.githubusercontent.com/52292872/75460948-64346f80-5982-11ea-9266-5bd7f3878d5d.png)

#### Environment
 - Omega Version : 1.19.0

**Comment by quentinguidee** [comment]
Good catch!

**Comment by M4xi1m3** [comment]
This is now working on omega-dev, don't know what fixed it tho.
