### ISSUE TITLE
Integrate boricj's stuff

### ISSUE THREAD

**Issue by boricj** [Omega-Numworks/Omega#29]
Now that I'm in, non-exhaustive list of pre-existing things to integrate from me:
- [x] https://github.com/numworks/epsilon/pull/947
- [x] https://github.com/numworks/epsilon/pull/746

Things to maybe unearth:
- [ ] https://github.com/numworks/epsilon/pull/311
- [ ] https://github.com/numworks/epsilon/pull/163

**Comment by quentinguidee** [comment]
* For https://github.com/numworks/epsilon/pull/947, I plan to merge it. Just one thing, the "Continuous integration" on simulators crashes. So we need to fix this first.
* For https://github.com/numworks/epsilon/pull/746, I'll merge it very soon!
* For https://github.com/numworks/epsilon/pull/311, a clock is really something I want to see on Omega!
* For https://github.com/numworks/epsilon/pull/163, I don't know what it is ahah but why not!

**Comment by quentinguidee** [comment]
(Note: numworks#746 related to #21)

**Comment by boricj** [comment]
Readily-mergable stuff has been merged.
