### ISSUE TITLE
Python issue with input

### ISSUE THREAD

**Issue by Chazmath** [Omega-Numworks/Omega#299]
#### Describe the bug
All of my scripts with input(“text “) are no longer working. 
Open the python shell and type input(“b “) and exe. Enter a value.  Python is not parsing this correctly. I get
Input(“b “)
b 6
‘66ut(“b “)’ 

In a script I get
ValueError: invalid syntax for integer with base 10 : ‘11()’

All my scripts work with older versions of below...

#### Environment
 - Omega Version: {go to settings > about > Omega Version and type the version here}
Epsilon 13.0.0
Omega 1.19.1
uPython 1.11.0

**Comment by M4xi1m3** [comment]
This is an issue from epsilon which has already been reported (#1374). We'll integrate the fix when it's available and release an update.

**Comment by quentinguidee** [comment]
Thanks anyway for this issue! I close this for the moment

**Comment by quentinguidee** [comment]
@Chazmath Numworks just fixed it : https://github.com/numworks/epsilon/pull/1377

We'll fix this on Omega as soon as possible :)
