### ISSUE TITLE
Add a shortcut for the character "Ω".

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#301]
#### What I want to see in the next version of Omega
I propose that `shift` + `9` make an Ω, present since Epsilon 13.0.0.
`9` because `alpha` + `9` makes an O. So this seems to me a logical choice.

**Comment by quentinguidee** [comment]
Done with 50a0fce958d2a5fbff85c76cb534ef477dfde2ad
Will be available in Omega 1.20
