### ISSUE TITLE
Bug in About Menu

### ISSUE THREAD

**Issue by windows9x95** [Omega-Numworks/Omega#306]
#### Describe the bug

> -EN

In the About menu, we can press "OK" on epsilon version and omega version that change the data on the screen (ex : epsilon 13.0.0 > d940216). When we do it and then we are going down, the change is discarded.
I think this isn't a good description, so I will do it in French too

> -FR 

Dans le menu à propos, on peut appuyer sur la touche "OK" sur "version d'epsilon" et "version d'omega", cela change la version écrite (par exemple pour "Version d'Epsilon", cela change 13.0.0 en d940216). Après avoir fait ça, en descendant ou montant dans le menu (En changeant la position des éléments affichés à l'écran), cela change l'état, par l'état par défaut (d940216 > 13.0.0).

#### Environment
 - Omega Version: 1.20 d940216

**Comment by LeGmask** [comment]
Dunno if it's really important ¯\_(ツ)_/¯

**Comment by M4xi1m3** [comment]
I think an issue like that was open one day on Epsilon. Don't think it's really worth fixing.

**Comment by LeGmask** [comment]
Okay maybe close this issue ? Because I think people doesn't look everyday for the commmit id in about.
