### ISSUE TITLE
Add script's size in Script Option

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#308]
#### What I want to see in the next version of Omega
Add python script's size in Script Option with https://github.com/numworks/epsilon/issues/1023

**Comment by RedGl0w** [comment]
This is partially relocated to #274

**Comment by quentinguidee** [comment]
As @RedGl0w says, it'll be done with #274.

I close this issue for now. If you want to integrate the compact display, feel free to comment :)

**Comment by quentinguidee** [comment]
Merged with a4af2942e60fd51f077afd5ca3e4095ab574aeb7 ; will be available in Omega 1.20
