### ISSUE TITLE
We can't save with nofrendo

### ISSUE THREAD

**Issue by Calvineries** [Omega-Numworks/Omega#314]
#### Describe the bug
Since the last update, nes games can no longer save, it's probably due of Epsilon 13.

#### Environment
 - Omega 19.1

**Comment by quentinguidee** [comment]
Yeah we're aware of this issue and we know why it occurs. It should be fixed with Omega 1.19.2 ^^

**Comment by quentinguidee** [comment]
Hi! Thank you for this issue,

@M4xi1m3 fixed this with [this PR](https://discordapp.com/channels/685936220395929600/685938974367285267/703679407868346463) :) To fix the issue, you have to re-download Nofrendo from https://m4xi1m3.github.io/nw-external-apps/index.html (it's not useful to update Omega to fix this issue)
