### ISSUE TITLE
simulate exam mode/simuler le mode examen

### ISSUE THREAD

**Issue by Woodkey** [Omega-Numworks/Omega#321]
Hello,
I explain my problem to you, I'm in high school and my exams are getting closer and closer. I would like to know if it is possible to simulate the exam mode on a numworks (in omega) by making the led flash as in exam mode. Or have the exam mode not erase the programs.

thank you in advance

-------------------------------------------------------------------------------------------------------

bonjour, 
je vous explique mon problème, je suis au lycée et mes examens se raproche de plus en plus. je voudrais savoir s'il est possible de simuler le mode examen sur une numworks (sous omega) en faisant clignoté la led comme en mode examen. Ou faire que le mode examen n'efface pas les programmes.

merci d'avance

**Comment by RedGl0w** [comment]
Salut !
Pour répondre à ta question, techniquement, c'est assez simple de le faire.
Cependant, nous somme des personnes honnêtes, et nous tennons à la réputation d'un fork qui reste dans la légalité (ce qui est déjà dûr), donc parmis les développeurs d'omega, personne ne va le faire. 
Bonne journée :) !

**Comment by Woodkey** [comment]
> Salut !
> Pour répondre à ta question, techniquement, c'est assez simple de le faire.
> Cependant, nous somme des personnes honnêtes, et nous tennons à la réputation d'un fork qui reste dans la légalité (ce qui est déjà dûr), donc parmis les développeurs d'omega, personne ne va le faire.
> Bonne journée :) !

Tout d'abord merci de ta réponse, je m'attendais a une réponse comme a votre. je comprends votre  point de vu et je ne voudrais pas entacher la réputation du fork.
Bonne journée a vous aussi

**Comment by quentinguidee** [comment]
🤣🤣🤣

Merveilleux poisson d'avril

**Comment by cent20net** [comment]
D'ailleurs je viendrais personnellement vérifier ta calculatrice le jour de l'épreuve Maxime, pour m'assurer que tu ne t'es pas codé un contournement du mode examen !

**Comment by RedGl0w** [comment]
> D'ailleurs je viendrais personnellement vérifier ta calculatrice le jour de l'épreuve Maxime, pour m'assurer que tu ne t'es pas codé un contournement du mode examen !

c'est ton élève ? X3

**Comment by M4xi1m3** [comment]
Absolument pas, et si on se retrouve à l'examen crois moi j'éclate de rire et je viens te serrer la main (mais pas de suite, COVID ^^)
