### ISSUE TITLE
Add OMEGA_THEME as compilating option

### ISSUE THREAD

**Issue by RedGl0w** [Omega-Numworks/Omega#33]
#### What I want to see in the next version of Omega

I would like to see an option in the compilation, which would be `OMEGA_THEME="epsilon"`, for changing theme of icons and omega.
The dark theme (https://github.com/Omega-Numworks/Omega/issues/8) could be a theme, and new icons (https://github.com/Omega-Numworks/Omega/issues/7) too :+1:

**Comment by quentinguidee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add OMEGA_THEME as compilating option](https://trello.com/c/jKDBJrgP/21-add-omegatheme-as-compilating-option)

**Comment by RedGl0w** [comment]
Close with https://github.com/Omega-Numworks/Omega/pull/100
