### ISSUE TITLE
Imperialism of "freedom" units

### ISSUE THREAD

**Issue by coco33920** [Omega-Numworks/Omega#337]
#### Describe the bug
Heya, since the addition of the freedom units the parser parse the units in the closest units which happen to sometimes be a freedom one, it's a major problem because in the majority of the countries we use the magical and super extra duper (cute) SI. 
So maybe to stop the imperialism of these units, add a compilation flag to not include them ? Or maybe better modify the parser to not parse into the imperial one with a setting ? 
I don't know which is the best way to do it
![image](https://user-images.githubusercontent.com/17108449/81285691-32194b00-9060-11ea-9c78-720894c3eb3c.png)

#### Environment
Latest Omega Dev build

**Comment by M4xi1m3** [comment]
Totally agree. I'd prefer the second  option, to not have to make the user compile the fw or have to make two versions.

**Comment by coco33920** [comment]
Indeed that's the best solution i think, however it's not that easy

**Comment by coco33920** [comment]
Fixed by #338
