### ISSUE TITLE
Display battery percentage

### ISSUE THREAD

**Issue by varszegimarcell** [Omega-Numworks/Omega#344]
#### What I want to see in the next version of Omega
I would be happy to see the charge level of my calculator's battery. I don't know how hard to accomplish this, but I will investigate the issue by myself.

**Comment by Gegenter** [comment]
First of all hello fellow Hungarian good to see you,

There was a similar issue not so long ago, our problem was/is that the voltmeter is not precise enough, the issue was #259. 

Come join our discord and lets see if we can do something about it!

**Comment by quentinguidee** [comment]
Thank you for this issue! It's something a lot of people want, but as @Gegenter said the voltmeter is unreliable for this task.

For now I close this issue ; feel free to comment if there is anything new !

**Comment by varszegimarcell** [comment]
Oh hey, I hadn't seen that older issue, sorry for the duplicate. After examining the circuit, it become pretty clear why does this is impossible to do. 

BTW, have you ever drained the battery of the calculator completely? To me, it never happened. I hadn't eveen charged it, except when I connectetd it to the computer, for firmware flashing/phyton script uploading. And I use my calculator oftenly, it is my go-to calc.

**Comment by quentinguidee** [comment]
Don’t worry for the duplicate, it’s not a problem! I just mark this as duplicate to keep track of this issue as best as I can ^^

Actually in terms of the battery I also never really had to charge mine! :)

**Comment by LeGmask** [comment]
Yop, for the battery I have already drained it many time btw but yeah is sooo long, but of you use the borijc clock it drained many times faster :p
