### ISSUE TITLE
The colors of the Omega buttons are darker than on Epsilon

### ISSUE THREAD

**Issue by A2drien** [Omega-Numworks/Omega#346]
#### Describe the bug
Look at the screenshots (especially the "Python Shell" button): the color of the buttons does not conform to the Epsilon color palette. You have to change this even if this choice was intentional, because a person with a less good view than the average may not be able to know whether the button is selected or not on Omega.
![Epsilon Blanc](https://user-images.githubusercontent.com/52292872/83951863-f9be8580-a834-11ea-969a-8510b4f77a46.png)
![Epsilon Dark](https://user-images.githubusercontent.com/52292872/83951861-f9be8580-a834-11ea-803c-a51f3b24f4b7.png)
![Omega Blanc](https://user-images.githubusercontent.com/52292872/83951865-fa571c00-a834-11ea-91f7-b0babe934974.png)
![Omega Dark](https://user-images.githubusercontent.com/52292872/83951957-b9abd280-a835-11ea-825e-2b719e446f9e.png)

#### Environment
 - Omega Version : 13.2.0 (N0100)

**Comment by quentinguidee** [comment]
Thanks! This issue should be fixed with 8d10e2884bb0bb33ae42db81af9298f6713b79e2 and will be available in Omega 1.20🙃
