### ISSUE TITLE
Shift + 0 for backslash in python editor

### ISSUE THREAD

**Issue by Tim-ats-d** [Omega-Numworks/Omega#348]
#### What I want to see in the next version of Omega

In the python editor, looking for the backslash is rather laborious (3 menus). Inserting the backslash with the key combination shift + 0 is one solution.

**Comment by LeGmask** [comment]
If you can assign me @quentinguidee ❤️ 👍 !

**Comment by quentinguidee** [comment]
@LeGmask Done!

**Comment by LeGmask** [comment]
As we say it is more logical to put the \ on alpha + x10^x, also as requested I will add the @ on alpha + Ans !

**Comment by quentinguidee** [comment]
Closed with #350 !
