### ISSUE TITLE
[BUG] - On latest omega-dev the alpha lock+back arrow put the % character 

### ISSUE THREAD

**Issue by LeGmask** [Omega-Numworks/Omega#352]
#### Describe the bug
On latest omega-dev the alpha lock put the % character  instead of remove character

#### Environment
 - Omega Version: Latest Omega-Dev

**Comment by RedGl0w** [comment]
This is a normal behaviour : I created https://github.com/Omega-Numworks/Omega/pull/329 for reverting the behaviour change for avoiding having conflicts with https://github.com/numworks/epsilon/pull/1479 (when @quentinguidee will pull upstream). This issue can be closed
