### ISSUE TITLE
Python heap size

### ISSUE THREAD

**Issue by kaimanox** [Omega-Numworks/Omega#357]
Hello everybody, I read that Omega has "32KB Python heap instead of 16KB one". Would it technically be possible to further increase this size? If yes, in which part of the code should I look to make such modification?

Thanks 
Tiziano

**Comment by RedGl0w** [comment]
Indeed, epsilon since version 13.2 has 32ko buffer for heap for python.

**Comment by M4xi1m3** [comment]
The python heap is defined here https://github.com/Omega-Numworks/Omega/blob/omega-dev/apps/code/app.h#L75, but to increase it you'll need to decrease other memory areas (maybe external heap?) or only include the python app.

**Comment by quentinguidee** [comment]
Hello! As answered, it is technically feasible. But if we wanted to increase this further, we would lose heap for the rest.

I close this issue since it has been answered. If you want more information, do not hesitate to comment this issue (or come to discuss it on the Discord! #16)

Thank you ^^
