### ISSUE TITLE
[Poincaré] Poincaré doesn't simplify completely

### ISSUE THREAD

**Issue by M4xi1m3** [Omega-Numworks/Omega#38]
#### Describe the bug
When inputting something like "1/(8\*x-2\*i\*x)+(8\*i)/(5\*x)", Poincaré doesn't simplify completely (see screenshots)

First pass :
![First pass](https://image.noelshack.com/fichiers/2019/44/5/1572615296-capture-d-ecran-du-2019-11-01-14-33-58.png)
Second pass :
![Second pass](https://image.noelshack.com/fichiers/2019/44/5/1572615296-capture-d-ecran-du-2019-11-01-14-34-17.png)

#### Environment
 - Omega Version: 1.12.1-0, on hardware and simulator.

**Comment by quentinguidee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Poincaré doesn't simplify completely](https://trello.com/c/byJYl0mb/19-poincar%C3%A9-doesnt-simplify-completely)

**Comment by quentinguidee** [comment]
This issue must be transferred to numworks/epsilon
