### ISSUE TITLE
Is Testing Mode Supported for Omega?

### ISSUE THREAD

**Issue by one-and-only** [Omega-Numworks/Omega#407]
My question is simple. Is testing mode supported in this OS? I would expect yes, but I just want to make sure.

**Comment by RedGl0w** [comment]
If you mean the hardware test app, it should be avaible even in exam mode in omega

**Comment by M4xi1m3** [comment]
What you mean is probably exam mode, and yes, it's available. We don't guarantee anything about its conformity, but we try to respect the laws as much as possible regarding exam mode.

**Comment by one-and-only** [comment]
@M4xi1m3 I meant exam mode, thanks for clarifying.
