### ISSUE TITLE
Not capturing KP_Enter?

### ISSUE THREAD

**Issue by fuzebox1** [Omega-Numworks/Omega#417]
Does the app not capture keypad enter as it does keyboard enter? Or is it just an issue on my end?

xev outputs keypad enter as KP_Enter, and keyboard enter as Return. Can i add KP_Enter in keybinds in the sourcecode?...

**Comment by RedGl0w** [comment]
Note : opened in epsilon too https://github.com/numworks/epsilon/issues/1678

**Comment by quentinguidee** [comment]
Thank you for this issue! However, as @RedGl0w said, the issue also appears Upstream. In Omega, we don't fix issues caused by Upstream. In facts, if this issue is solved in Omega and then in Epsilon, it will cause conflicts while merging upstream.
