### ISSUE TITLE
Miles to kilometers conversion doesn't work

### ISSUE THREAD

**Issue by ladyeklipse** [Omega-Numworks/Omega#420]
#### Describe the bug
![image](https://user-images.githubusercontent.com/4990107/98373088-68ec1000-2047-11eb-9ddf-0740890b6e07.png)

#### Environment
 - Omega Version: 1.20.2

**Comment by RedGl0w** [comment]
Epsilon 15 will add imperial units support, and conversion between si and imperial will work. Will be close when epsilon will be merged in omega

**Comment by jneb** [comment]
This will probably also fix the bug I found: 1_m/35_in becomes .283_ft/_m

**Comment by M4xi1m3** [comment]
> Will be close when epsilon will be merged in omega

Well I think it can be closed now.
