### ISSUE TITLE
I seem to be quite stupid...

### ISSUE THREAD

**Issue by raphaelritz** [Omega-Numworks/Omega#421]
Hi. Let me start by saying that I am very inexperienced.
I just got a brand-new Numworks n0110 and am trying to install the newest version (01.20.3-E14.4.1) of Omega in the epsilon_dark theme onto it. I am on a Windows 10 computer and followed every step of this tutorial: https://github.com/Omega-Numworks/Omega/wiki/Installation (while adding "THEME_NAME=epsilon_dark" after the "make" command). Everything seemed to work just fine up to the `make MODEL=n0110 epsilon_flash` part.
It just says:

```
    ____
   / __ \____ ___  ___  ____ _____ _
  / / / / __ `__ \/ _ \/ __ `/ __ `/
 / /_/ / / / / / /  __/ /_/ / /_/ /
 \____/_/ /_/ /_/\___/\__, /\__,_/
                     /____/
          - Omega does what Epsilon't

Building O1.20.3-E14.4.1
  Targetting Numworks n0110
    Building on Windows x86

DFU     epsilon_flash
INFO    About to flash your device. Please plug your device to your computer
        using an USB cable and press at the same time the 6 key and the RESET
        button on the back of your device.
```
and never actually starts to install anything, as if it didn't detect the device. This happens no matter how often I press reset or reset+6 and no matter what usb port or cable I use. I am currently running Omega version 1.20.3 and Epsilon version 14.4.1 on the device. I apologize for such a foolish question but please, help me before I snap and start shredding and eating my Numworks calculator.

**Comment by quentinguidee** [comment]
Hi! The epsilon_flash part on Windows 10 is not working. It only works well on Linux and macOS. We suggest you to compile the binpacks (see `README.md`) and to flash it on your calculator using this tutorial (part II - https://tiplanet.org/forum/viewtopic.php?f=99&t=23196&p=248745&lang=en#p248745).

**Comment by raphaelritz** [comment]
Thank you so much for the quick answer, I will do that immediately! :D
