### ISSUE TITLE
[Poincaré] Out of memory with certain operations

### ISSUE THREAD

**Issue by M4xi1m3** [Omega-Numworks/Omega#44]
#### Describe the bug
When inputting (1)/(x^2) + (1)/(3x), the calculator returns an out of memory, but when inputting (x^-2) + (1)/(3x), it works correctly.
Seems to do that every time you use x^n as denominator.

#### Environment
 - Omega Version: 1.13.0-0
 - Model: n0110

**Comment by M4xi1m3** [comment]
Seems to not be reproducible in later versions of Omega.

**Comment by quentinguidee** [comment]
Huh I just tried and get the same error on n0100 x)

**Comment by M4xi1m3** [comment]
Ok I found how to reproduce it. It only happens in real mode. When you allow complex numbers the issue problem isn't there.

**Comment by M4xi1m3** [comment]
![](https://image.noelshack.com/fichiers/2019/45/2/1572963773-capture-d-ecran-du-2019-11-05-15-22-11.png)
Found out that it makes a lot of recurrent calls, maybe an infinite loop.

**Comment by quentinguidee** [comment]
Bug transferred to upstream: https://github.com/numworks/epsilon/issues/1181

**Comment by quentinguidee** [comment]
Bug fixed upstream and merged with **Ω1.15.5**! https://github.com/numworks/epsilon/pull/1194
