### ISSUE TITLE
developping error : ab-a*b doesn't simplify to 0

### ISSUE THREAD

**Issue by Draeggon** [Omega-Numworks/Omega#442]
I can't take a screen but if you enter :
   ab-ab you get 0
   a*b-a*b you get 0
  but ab-a*b you didn't get 0
wich is problemating when developping things like (a+b)(a²-ab+b²)

**Comment by A2drien** [comment]
This is not a bug : the calculator understands _ab_ as a variable which has the name **ab**, not as the variable **a** multiplied by the variable **b**.
