### ISSUE TITLE
Cannot type "v" or "u"

### ISSUE THREAD

**Issue by theTisch21** [Omega-Numworks/Omega#444]
#### Describe the bug
Typing "v" or "u" anywhere except python causes a syntax error, rather than returning the variable itself like for "a" or "b"
I also cannot store a number to either of those as variables
Note: It only causes an error when using lowercase "v" or lowercase "u", capitals work fine.

#### Screenshots:
![image](https://user-images.githubusercontent.com/20461232/105271663-c410a780-5b4c-11eb-9c45-74fa00561340.png)
![image](https://user-images.githubusercontent.com/20461232/105272586-844abf80-5b4e-11eb-9b12-99c773b0a8e7.png)

#### Steps To Reproduce
1. Go to the 'calculation' app
2. Type 'v' or 'u'
3. Press OK
4. See syntax error
5. Go to the 'functions' app
6. Create a new function
7. Type 'v' or 'u' in the function
8. See syntax error

#### Environment
The web simulator and my N0110, both latest version, 1.20.2

**Comment by theTisch21** [comment]
I did some messing around with Epsilon's web simulator, and found the same bug. I've opened a similar issue on their repository: 
https://github.com/numworks/epsilon/issues/1751
As this isn't an Omega issue anymore, I've decided to close this issue (At least for now).

**Comment by quentinguidee** [comment]
Thanks! However, as said upstream, it's not an issue. More info : https://github.com/numworks/epsilon/issues/1622
