### ISSUE TITLE
[BETA-1.21] Reset automatique

### ISSUE THREAD

**Issue by Cyber-Thibaut** [Omega-Numworks/Omega#454]
**Describe the bug**
The calculator resets itself when you press the arrow at the bottom of the pad only in the general menu.

**To Reproduce**
1. Go to Home Screen
2. Long press the down arrow
3. See error

**Info :**
 - Omega Version: 1.21
 - Discord username: Spider Man#4872

**Comment by Cyber-Thibaut** [comment]
[The video of the problem who I have.](https://youtu.be/JXn_8aGn-H8)

**Comment by M4xi1m3** [comment]
After some testing, this seem to happen because of the external icons. This will be a pain to debug. As a temporary solution I'd recommend installing external apps without the experimental icons support.

**Comment by M4xi1m3** [comment]
Fixed by #473
