### ISSUE TITLE
Small graphical bug with subtabs in probability app

### ISSUE THREAD

**Issue by Trixciel** [Omega-Numworks/Omega#472]
**Describe the bug**
1 line of pixels are missing from the subtab when showing the graph of a probability model.

**To Reproduce**
1. Go to the probability app
2. Choose a probability model
3. Take a close look at the bottom of the dark grey subtab
4. Show the graph 
5. Look at the bottom of the current subtab
6. See the graphical bug (if necessary press return and ok back and forth while looking at it)

**Expected behavior**
The subtab shouldn't change size (or shouldn't get drawn stuff on it)

**Pictures (No screenshots)**
![IMG_20210214_180640](https://user-images.githubusercontent.com/59417613/107883497-a508f980-6eef-11eb-942c-19e104f53b70.jpg)
![IMG_20210214_180645](https://user-images.githubusercontent.com/59417613/107883498-a6d2bd00-6eef-11eb-9911-4c330a265c01.jpg)

**Desktop (please complete the following information):**
 - Omega Version: 1.20.2 and 1.21 Beta-1

**Comment by M4xi1m3** [comment]
Thank you for the bug report. This issue is also present in epsilon. You should open an issue there. I'll keep this one open until it's done.

**Comment by Trixciel** [comment]
I opened an issue in Epsilon, thanks for your help.

**Comment by M4xi1m3** [comment]
Thank you very much. Upstream issue : https://github.com/numworks/epsilon/issues/1782. I'm closing here.
