### ISSUE TITLE
[BETA-1.21] Crash when scrolling in the menu

### ISSUE THREAD

**Issue by TheWeatherKill** [Omega-Numworks/Omega#482]
**Describe the bug**
The calculator crash and return to zero when scrolling down oustside the normal with external app

**To Reproduce**
(need at least 2 external apps)
1. Go in the menu
2. Go down until the first app (KhiCAS for me)
3. Press down button once
4. See all your setting disappear

**Expected behavior**
The calculator mustn't crash and return to zero when scrolling down oustside the normal with external app like in 1.20.3

**Screenshots**
I can give you screenshots later

**Desktop (please complete the following information):**
 - Omega Version: 1.21.0-B1
 - Discord username: TheWeatherKill#1337

**Comment by quentinguidee** [comment]
Hi! Thanks for this issue! If I understand well, it sounds like the same as #454 (which has been fixed in the dev branch). I'm closing for the moment, feel free to comment if it should be reopened.
