### ISSUE TITLE
[BETA-1.21] Cube root computation error for negative radicands

### ISSUE THREAD

**Issue by klou23** [Omega-Numworks/Omega#486]
**Describe the bug**
In the calculation app, calculation of cube roots seems to be completely off.

**To Reproduce**
Steps to reproduce the behavior (This is just one example):
1. Go to the calculation app.
2. Press the toolbox button
3. Scroll down and select the root function
4. Make the index of the root 3
5. Make the radicand -1
6. Press EXE
7. The result the calculator shows is a complex number

**Expected behavior**
The calculator should return -1 when calculating the cube root of -1. The omega web simulator running 1.20.3 seems to be computing the correct answers

**Screenshots**
I don't know how to take screenshots of the physical calculator, but here is an image of the calculator computing the cube root of -1 and -8 incorrectly
![IMG_0157](https://user-images.githubusercontent.com/58053969/108811040-ba25fe00-7569-11eb-9351-3c283e253dcb.jpg)

**Desktop (please complete the following information):**
 - Omega Version: 1.21.0-B1
 - Discord username: kevinl2005#1425

**Comment by RedGl0w** [comment]
Clearly not broken : when complex mode is activated, the only displayed solution of the root is always the complex one (try switching back in the settings to Real complex mode). This behavior is exactly the same on epsilon, and I opened an issue a long time ago to add in additional result the Real root too :p https://github.com/numworks/epsilon/issues/1617
