### ISSUE TITLE
Atomic: Incorrect electron configurations for some elements

### ISSUE THREAD

**Issue by klou23** [Omega-Numworks/Omega#514]
**Describe the bug**
In the Atomic app, some of the elements in groups 6 and 12 have incorrect electron configurations (Cr, Mo, Cu, Ag, Au).

**To Reproduce**
1. Go to Atomic app
2. Scroll over to Chromium (Cr)
3. Press "OK"
4. Scroll down to the electron configuration
5. The displayed electron configuration ([Ar]4s2 3d4) is incorrect

**Expected behavior**
The atomic app should display the correct electron configuration.

**Screenshots**
![IMG_0188](https://user-images.githubusercontent.com/58053969/111236144-cffe7000-85b7-11eb-8da9-1067c8a4f01a.PNG)

**Desktop (please complete the following information):**
 - Omega Version: 1.22.0

**Comment by RedGl0w** [comment]
Indeed, currently the atomic app can't handle the exception (for instance, in Wikipedia fr, these atoms are marked in red). This is not really a bug, but more a feature request so :p

**Comment by RedGl0w** [comment]
Should be fixed with https://github.com/RedGl0w/atomic/commit/956af933f3d53e19b43e6a354a1ce27f49a21f03
