### ISSUE TITLE
When selecting a country the info message is white text on a white background when I have dark mode

### ISSUE THREAD

**Issue by LukasAppleFan** [Omega-Numworks/Omega#534]
**Describe the bug**
When I want to select a country the message above the country list appears all white when I use the dark version of Omega.

**To Reproduce**
1. Go to settings
2. Click on Country
3. See error

**Expected behavior**
The text should be white on a black background.

**Screenshots**
![FB303390-A2A4-4237-B82B-91AB676C8F87](https://user-images.githubusercontent.com/41242166/117935666-3f68b580-b304-11eb-8530-74bc5fffb66a.jpeg)

**Desktop (please complete the following information):**
 - Omega Version: 15.3.1

**Comment by fime-space** [comment]
That's also present on the Epsilon dark theme. Actually, we can distinguish some text because of the background appear to be a little bit darker than the text.

**Comment by RedGl0w** [comment]
It should be fixed with https://github.com/Omega-Numworks/Omega/pull/535
You can comment if you still have an issue
