### ISSUE TITLE
No splash screen on the epsilon light and dark theme

### ISSUE THREAD

**Issue by fime-space** [Omega-Numworks/Omega#541]
**Describe the bug**
When the calculator is reseted or rebooted, the spash screen (idk how it's really called, but that's just the logo of omega) doesn't appear.

**To Reproduce**
1. Compile the OS with the Epsilon dark theme (if i remember correctly, that also append on the epsilon light theme)
2. Reset the calculator
3. See error : the main menu is directly displayed without the splash screen

**Expected behavior**
The omega logo should be displayed.

**Desktop (please complete the following information):**
 - Omega Version: 1.22.1 with epsilon dark theme

**Comment by M4xi1m3** [comment]
You have to use the target epsilon.onboarding to have the splash screen.

**Comment by fime-space** [comment]
> You have to use the target epsilon.onboarding to have the splash screen.

hummm would'nt it be more intuitive to set it by default ?

**Comment by RedGl0w** [comment]
> hummm would'nt it be more intuitive to set it by default ?

On omega there is the exact same behaviour as epsilon. I don't think this is necessary to change...

**Comment by fime-space** [comment]
okay, sorry to have cluttered the issues. I'll close it.
