### ISSUE TITLE
Can't connect to NumWorks Workshop to exchange Python scripts

### ISSUE THREAD

**Issue by AlexPMLikesNumWorks** [Omega-Numworks/Omega#55]
**Describe the bug**

With this version, I cannot connect the calculator to NumWorks' Workshop for Python scripts. All connection attempts end up in having the web page stating that the calculator is not connected.

When I try to force-download Python scripts, web page says that the calculator's memory is corrupted and that I have to update to the latest version.

Is upload/download of Python scripts supported in Omega 1.10.1-0? 

**Environment**
 - Omega version : 1.10.1-0
 - Model : _unknown_

**Comment by quentinguidee** [comment]
Hi! Thanks for using Omega!

Sadly, the Workshop don't work with Omega. We don't know exactly if Numworks restrict the workshop only for Epsilon, or if we have a bug in our code...

If I'm not wrong, we already have an issue opened for this bug: see #10 (but I don't know if you encounter exactly the same problem).

**Comment by AlexPMLikesNumWorks** [comment]
Yes I agree, it is partly a duplicate of #10 (#10 is about crashing the calculator, which does not happen).
I experience no crash, I just cannot up/download Python scripts (because of a reluctant Workshop).

**Comment by quentinguidee** [comment]
Issue merged with https://github.com/Omega-Numworks/Omega/issues/10#issuecomment-551191949

**Comment by quentinguidee** [comment]
@AlexPMLikesNumWorks Issue fixed!
