### ISSUE TITLE
Brightness issue with Omega 2.0.0 public release

### ISSUE THREAD

**Issue by melon-husk** [Omega-Numworks/Omega#565]
**Describe the bug**
There are two issues with brightness control, first, if you set the brightness to minimum, the actual brightness is maximum,
second, even if your brightness is set to a low value, lets say 10%, after 15-20 seconds, it automatically sets it to maximum and stays there until a user click a button, then the brightness goes down to the set value, ie 10%

**To Reproduce**
1. Go to Settings
2. Change brightness slider to minimum
3. See the brightness issue

**Expected behavior**
The brightness should be minimum, when we set it to minimum. And after 15-20 seconds, it shouldn't set it to max and stay there until the user clicks a button.

**Desktop (please complete the following information):**
 - Omega Version: 2.0.0

**Comment by Tunas1337** [comment]
Possibly related: the lowest brightness step of the shift+plus/minus hotkey when Omega is first flashed and reset into is actually max brightness. This issue resolves itself once you pass onboarding and power-cycle the calculator (but don't reset.) If needed I'll open a separate issue to track that and link it here, but I'm 99% certain the same fix targets both.

**Comment by melon-husk** [comment]
Hmm, yes, that did fix both issues, thanks !
