### ISSUE TITLE
Omega 2.0 hides numworks model, omega version and epsilon version

### ISSUE THREAD

**Issue by Golem642** [Omega-Numworks/Omega#569]
**Describe the bug**
Omega and Upsilon doesn't recognise the calculator model anymore

**To Reproduce**
1. Install Omega 2.0 on your numworks

**Expected behavior**
Model will appear as N??? and it will no longer possible to install software like Omega and Upsilon without using recovery mode. Also it cannot detect Omega and Epsilon version, even with recovery

**Screenshots**
![image](https://user-images.githubusercontent.com/65229557/162324866-6343ec07-d1df-4d17-b805-32d2dfddb18e.png)

**Desktop (please complete the following information):**
 - Omega Version: 2.0

**Comment by Yaya-Cout** [comment]
I think it is because the PlatformInfo has moved…

---

Je pense que c'est parce que le platformInfo à bougé…

**Comment by QingchenWait** [comment]
I have met the same problem.
My initial Epsilon Version was 15.5.0.

**Comment by Yaya-Cout** [comment]
For the model, it's fixed in Upsilon.js and for the version, I started to find a fix, but I can't detect the active slot.
