### ISSUE TITLE
 Someone's Numworks installation problem

### ISSUE THREAD

**Issue by LeskaHub** [Omega-Numworks/Omega#576]
Hello, just found a new bug: when I click on detect calculator, I found my numworks ("Numworks Calculator"), I click on it and connect it but after, I see this: (image) and when I click on Install omega, it says "Installing Omega O2.0.2-E15. Please do not unplug your Numworks.", I waited an hour but it dosen't changed.

My calc is on version N0110 (18.2.3)

I triyed to click on recovery but my calc dosen't show in the connect tab.

Please help me

![Screenshot 2022-05-28 144250](https://user-images.githubusercontent.com/82216890/170825997-2fb88d91-10ee-4a23-bd58-f9efed84cd23.png)

**Comment by quentinguidee** [comment]
Well, that's not a bug. You must jailbreak your calculator with [Phi](https://guide.getomega.dev/) first. Our installer is not able to retrieve your calculator information because of that 😄

**Comment by LeskaHub** [comment]
> Well, that's not a bug. You must jailbreak your calculator with [Phi](https://guide.getomega.dev/) first. Our installer is not able to retrieve your calculator information because of that 😄

Wait

**Comment by LeskaHub** [comment]
> Well, that's not a bug. You must jailbreak your calculator with [Phi](https://guide.getomega.dev/) first. Our installer is not able to retrieve your calculator information because of that 😄

Ok but when I try to jailbreak it, it shows this: 
![image](https://user-images.githubusercontent.com/82216890/170826556-fdcb6139-5063-4587-8591-fa978b79add8.png)
(I used https://phi.getomega.dev/)

**Comment by quentinguidee** [comment]
Please read the Guide carefully. If you have more questions, I suggest you to join our discord. It will be easier to help you ;) https://discord.gg/JpmjSH3

**Comment by LeskaHub** [comment]
Ok thanks
