### ISSUE TITLE
Add android simulator to Fdroid store

### ISSUE THREAD

**Issue by uranuspucksaxophone** [Omega-Numworks/Omega#583]
See: https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by quentinguidee** [comment]
Hi, thank you for this issue!

Unfortunately, the CC BY-NC-SA license is not compatible with the f-droid definition of FOSS. Therefore we cannot upload it to this store

**Comment by quentinguidee** [comment]
This is from Epsilon :/ For us, CC licenses are not good licenses for code. But unfortunately this is a choice made by Numworks and we have to comply

**Comment by quentinguidee** [comment]
> And couldn't we make a clean room re implementation of omega that is truly open-source?

There is a projet called nw-rs/rustworks on GitHub that tried to achieve this goal. But as you said it will take time 😅
