### ISSUE TITLE
Impossible to install external apps and calculator not detected properly after 2.0.2 update

### ISSUE THREAD

**Issue by BanbanProduction** [Omega-Numworks/Omega#587]
**Describe the bug**
Impossible to install external app after installing the update 2.0.2. Moreover the calculator isn't detected properly by the install page, as you can see on the first screenshot

**To Reproduce**
0. I have a N0110 calculator with omega in the 1.23.0 version, with apps installed : Nofrendo and Periodic. 
1. Install the last update 2.0.2 from the website. Everything looks normal and the installation complete.
2. Go to external apps installation page : https://external.getomega.dev/
3. Select any app and/or any file
4. Click install
5. Error occurred, second screenshot

**Expected behavior**
So I expected it to install apps and detect properly the calculator.
Now I can not install apps, but old ones are still there (Nofrendo and Periodic). I can't install an other version of Omega, I tried with the old one 1.23.0 and new one 2.0.2 but the loading bar doesn't move and nothing happens, third screenshot.
I tried reset but it didn't changed anything.

**Screenshots**
Calculator not detected properly :
![Calculator not detected properly](https://user-images.githubusercontent.com/79019044/186233879-ea5d436d-70c3-44a7-9bf5-ffe487ca55e1.png)
Error while trying to install apps :
![Error installation of external apps](https://user-images.githubusercontent.com/79019044/186233868-9255ee6a-b1d2-4caf-b41a-a01a94fceec4.png)
Impossible to install an other version :
![Impossible to install an other version](https://user-images.githubusercontent.com/79019044/186234977-23706bba-e578-495c-86a1-ecca6e68064a.png)

**Desktop (please complete the following information):**
 - Omega Version: 2.0.2

**Comment by Yaya-Cout** [comment]
Can you close other tabs ? `Unable to claim interface` error mean that the calculator is already used by another tab. The last screenshot should not be problematic.

**Comment by BanbanProduction** [comment]
Thank you it solved the problem, stupid of me to don't try that before. But there is still one problem : I can't install an other version without using recovery mode.

**Comment by Yaya-Cout** [comment]
It's a known bug that I fixed in a pull request for Upsilon.js that has not been published to the NPM registry.

**Comment by BanbanProduction** [comment]
Thank you very much for those precious help and information !
