### ISSUE TITLE
Installing Failure

### ISSUE THREAD

**Issue by MoDZzARELLA** [Omega-Numworks/Omega#597]
When I installed the lastest Numworks update and wanted to install Omega then, when I was on the "Install" page, my calculator kept connecting and disconnecting but it was the ONLY page which the one it did that

The Numworks version was the 20.3.0

**Comment by Yaya-Cout** [comment]
You need to downgrade before using Omega. Follow this guide to do that : https://guide.getomega.dev/. If you can't get it working, please join Omega's Discord Server (link is in the guide)
