### ISSUE TITLE
MARCHE PAS

### ISSUE THREAD

**Issue by lucassssssss-ops** [Omega-Numworks/Omega#603]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Omega Version: [go to settings > about > Omega Version and type the version here]

**Comment by quentinguidee** [comment]
Please follow our [code of conduct](https://github.com/Omega-Numworks/Omega/blob/omega-master/CODE_OF_CONDUCT.md) and fill-in useful issues. Another issue like this may result in a ban of your user account from our repositories.
