### ISSUE TITLE
Can't fully install any omega version since 1.23

### ISSUE THREAD

**Issue by Lucagranger** [Omega-Numworks/Omega#606]
**Describe the bug**
I have a numwork N0110 wich was in the latest epsilon version, I followed a guide to downgrade it using a raspberry pi. It worked without any isues. And at the time i could upgrade it with the latest omega v. But since the 2. series, when I try. It just keep on charging, I've try to leave it on for 2h, but nothing. And when I unplug it, in the settings it says that it is on the latest version but then my PC does not recognise it anymore, so i'm stuck and i have to go into recovery mode

**To Reproduce**
1. Update Omega past 1.23
2. wait
3. wait
4. nothing is happening

**Expected behavior**
I'm expecting it to update.

**Desktop (please complete the following information):**
 - Update between 1.23 and any further

**Comment by quentinguidee** [comment]
For installation assistance, you can join our Discord server at https://discord.gg/JpmjSH3
