### ISSUE TITLE
Need to find a better way to store exam mode state.

### ISSUE THREAD

**Issue by M4xi1m3** [Omega-Numworks/Omega#63]
#### Describe the bug
Currently, the exam mode status is not directly accessible trough ion, but is accessed from apps/global_preferences.h (only once, in `ion/src/device/n0110/drivers/led.cpp`), which is a layer violation. This is due to my dirty fix to get led blinking when the numworks is off.
Also, the way epsilon stores if the calculator is in exam mode doesn't comply with french laws, since you should be only able to exit exam mode by plugging your calculator (right now you can press reset, it will make it go out of exam mode).

#### Environment
 - Omega Version: d14215b. First problem is only happening with n0110, second one with both.

**Comment by quentinguidee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move the per apps settings to the apps](https://trello.com/c/owaDm5hW/1-move-the-per-apps-settings-to-the-apps)

**Comment by quentinguidee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Need to find a better way to store exam mode state](https://trello.com/c/MA1A4aOL/2-need-to-find-a-better-way-to-store-exam-mode-state)

**Comment by quentinguidee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Screen standby](https://trello.com/c/LVg3eVD2/12-screen-standby)

**Comment by quentinguidee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Need to find a better way to store exam mode state](https://trello.com/c/6ijpJPuR/14-need-to-find-a-better-way-to-store-exam-mode-state)

**Comment by quentinguidee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Poincaré doesn't simplify completely](https://trello.com/c/byJYl0mb/19-poincar%C3%A9-doesnt-simplify-completely)

**Comment by quentinguidee** [comment]
Since we merged this PR (https://github.com/numworks/epsilon/pull/1239), I think this issue if fixed. Re open it if i'm wrong
