### ISSUE TITLE
Make a dockerfile for building more easily

### ISSUE THREAD

**Issue by RedGl0w** [Omega-Numworks/Omega#69]
#### What I want to see in the next version of Omega
I would like to have a dockerfile on dockerhub for novice people who wants to build omega, without having trouble with all dependencies :smile:

**Comment by quentinguidee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make a dockerfile for building more easily](https://trello.com/c/RR0Gg6fH/31-make-a-dockerfile-for-building-more-easily)

**Comment by quentinguidee** [comment]
Closed with #358 !
