### ISSUE TITLE
Change hardware popup loction

### ISSUE THREAD

**Issue by RedGl0w** [Omega-Numworks/Omega#72]
**Describe the bug**
When you press 6 on contributors, the hardware test popup get opened. it should be on FCC ID

**Comment by RedGl0w** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [change hardware popup location](https://trello.com/c/sZaPagCq/37-change-hardware-popup-location)

**Comment by RedGl0w** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [change hardware popup location](https://trello.com/c/sZaPagCq/37-change-hardware-popup-location)

**Comment by MixedMatched** [comment]
Code from upstream always points to the last row, not specifically the FCC row.

**Comment by RedGl0w** [comment]
fixed with https://github.com/Omega-Numworks/Omega/pull/73
