### ISSUE TITLE
Theme manager

### ISSUE THREAD

**Issue by quentinguidee** [Omega-Numworks/Omega#78]
#### What I want to see in the next version of Omega
A theme engine. Every colors could be defined in a json file and processed with Python before installing.

#33 Adding a compilation option will be done later. So, i split the issue in two parts.

**Comment by quentinguidee** [comment]
https://github.com/Omega-Numworks/Omega-Themes

**Comment by M4xi1m3** [comment]
I think this issue can be closed now (#77 and #104)
