### ISSUE TITLE
Plans for Dark Mode

### ISSUE THREAD

**Issue by MixedMatched** [Omega-Numworks/Omega#8]
#### What I want to see in the next version of LavaOS
I don't think we should just implement dark mode. Instead, we should implement a full theming engine.* Not only would it be future-proofed, it would also be faster than doing if checks for every component.

* By theming-engine, I mean in-code, not in terms of GUI.

**Comment by quentinguidee** [comment]
I totally agree! 

And to implement all this, let's start doing another light theme? For example, just change the orange by another color. So, we can focusing on the engine's code before dealing with the choice of colors and icons.

**Comment by MixedMatched** [comment]
Changing colors should be very easy, but I'm not sure about the icons.

**Comment by RedGl0w** [comment]
The dark theme can be made by activating a specific output of the micro controller, which inverts all the color of the screen (which would be more simple).
https://github.com/numworks/epsilon/pull/947

**Comment by boricj** [comment]
To correct the last comment, numworks#947 does not rely on color inversion of the display controller. Instead it performs inline post-processing of drawing commands, allowing for effects like gamma correction on all platforms. I've recently updated the PR with epsilon's master.

**Comment by RedGl0w** [comment]
https://github.com/Omega-Numworks/Omega/issues/33

**Comment by quentinguidee** [comment]
See #78
