### ISSUE TITLE
Selector gets “stuck” on the home screen

### ISSUE THREAD

**Issue by 0b101** [Omega-Numworks/Omega#85]
#### Describe the bug
If your on the home screen (app selection page) with the selector all the way to the right and you try to scroll down to settings the selector gets stuck at sequences and can’t go down any further. I understand that this is because there is technically nothing directly under it, but ideally it should just jump one app left and down to settings.

#### Environment
- Omega Version: 1.17

**Comment by RedGl0w** [comment]
I've an idea to correct it!

**Comment by RedGl0w** [comment]
Ok I understood why this happens :
`SelectableTableView::selectCellAtLocation` (https://github.com/Omega-Numworks/Omega/blob/9d315cd64c46bda63389b1fb8c70901f46e2fbe7/escher/src/selectable_table_view.cpp#L75-L116) should return false when you go to a uncompleted line, and this line hasn't got the cell you told it. Whithout this *issue*, you just have to add: 
`  if (event == Ion::Events::Down && selectionDataSource()->selectedRow() < numberOfRows()){
    return m_view.selectableTableView()->selectCellAtLocation(0, selectionDataSource()->selectedRow()+1);
  }`
to https://github.com/Omega-Numworks/Omega/blob/9d315cd64c46bda63389b1fb8c70901f46e2fbe7/apps/home/controller.cpp#L70.

For the first issue, I've absolutely no idea to correct it, but I'm trying to find one...

**Comment by quentinguidee** [comment]
Fixed with #393 !

**Comment by M4xi1m3** [comment]
Fixed by #460
