### ISSUE TITLE
Exam mode popup - problem with colors

### ISSUE THREAD

**Issue by grandben49** [Omega-Numworks/Omega#90]
#### Describe the bug

~~En testant rapidement, j'ai eu un problème avec le mode examen, en tout cas pour l'activation/désactivation:~~

~~La case "annuler" est à gauche et la case "valider" est à droite, mais pour se déplacer de gauche à droite il faut faire gauche et pour se déplacer de droite à gauche il faut faire droite. De même l'action sur la case "valider" correspond à annuler et inversement.~~

By testing quickly, I had a problem with the exam mode, at least for activation / deactivation:

The "cancel" box is on the left and the "validate" box is on the right, but to move from left to right you have to go left and to move from right to left you have to go right. Similarly, the action on the `validate` box corresponds to cancel and vice versa.

#### Environment
 - Omega Version: 1.17.0-0
- Model: n0100

**Comment by MixedMatched** [comment]
Je ne peux pas reproduire ce bogue. Êtes-vous sûr que ce n'est pas un problème avec le jeu de couleurs? Aussi, désolé si ce n'est pas le bon français, j'utilise google translate.

**Comment by M4xi1m3** [comment]
Justement, ceci ne semble pas être un bug (je n'arrive pas à le reproduire moi-même). Je pense que vous confondez le bouton sélectionné et le non-sélectionné (ça m'est arrivé au début). Le bouton sélectionné devrais être le plus foncé.

**Comment by MixedMatched** [comment]
Cependant, je pense que les couleurs devraient être changées, car ce serait plus intuitif.

**Comment by quentinguidee** [comment]
Bonjour @grandben49 ! Effectivement, je crois que ce sont les couleurs qui sont mal choisies; nous allons les modifier dès que possible et vous notifions quand le problème est fixé 😉

**Comment by grandben49** [comment]
Bonjour et merci pour votre réponse.

Je n'avais effectivement jamais lancé le mode "examen" et donc j'ai été surpris par le problème des couleurs.

J'essaie d'aller plus loin en tentant de compiler omega.

Je fais les manipulations sous W10 en utilisant Msys2.
Je suis les différents tuto où tout semble se dérouler correctement (pas vu de message d'erreur) et j'ai un problème à partir du make:

$ make MODEL=n0100 clean
make: pkg-config: Command not found
make: pkg-config: Command not found
/bin/sh: pkg-config : commande introuvable
CLEAN

puis
$ make MODEL=n0100 USERNAME="" -j8
make: pkg-config: Command not found
make: pkg-config: Command not found
/bin/sh: pkg-config : commande introuvable
CXX     ion/src/device/n0100/drivers/board.o
CXX     ion/src/device/n0100/drivers/reset.o
make: arm-none-eabi-g++: Command not found
make: *** [build/rules.mk:15: output/release/device/n0100/ion/src/device/n0100/drivers/board.o] Error 127
make: *** Attente des tâches non terminées....
make: arm-none-eabi-g++: Command not found
make: *** [build/rules.mk:15: output/release/device/n0100/ion/src/device/n0100/drivers/reset.o] Error 127

Mon anglais est basique mais je comprends qu'il me manque des commandes...pourtant gcc-arm a bien été installé suivant les tutos.

J'ai également essayé avec le sous système linux sous W10, mais je bloque sur les étapes à partir de la décompression (j'ai bien téléchargé gcc-arm sur le bureau).

Pourriez-vous m'aider à aller plus loin.

Merci pour le travail que vous avez déjà effectué sur Omega.
Grandben49


________________________________
De : Quentin <notifications@github.com>
Envoyé : lundi 9 décembre 2019 23:35
À : Omega-Numworks/Omega <Omega@noreply.github.com>
Cc : grandben49 <grandben49@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [Omega-Numworks/Omega] Problème mode examen (#90)


Bonjour @grandben49<https://github.com/grandben49> ! Effectivement, je crois que ce sont les couleurs qui sont mal choisies; nous allons les modifier dès que possible et vous notifions quand le problème est fixé 😉

**Comment by quentinguidee** [comment]
**FR**

@grandben49 Désolé pour la réponse tardive, je n'avais pas vu ton commentaire. Pour tout problème d'installation, tu peux rejoindre notre Slack (sur le channel #omega-support-fr), nous t'aiderons avec plaisir!

Sinon, je viens de fixer ce bug sur la version stable (donc sur la branche `omega-master`). La version est nommée Omega 1.17.2

Merci pour ce rapport de bug!

**EN**

@grandben49 Sorry for the late reply, I hadn't seen your comment. For any installation problem, you can join our Slack (on the channel # omega-support-fr), we will be happy to help you!

Otherwise, I just fixed this bug on the stable version (so on the `omega-master` branch). The version is named Omega 1.17.2

Thank you for this bug report!
